{
  "hash": "16ab5b0c4030c0a5bf171f08633f5aa0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Dataset y enriquecimiento\"\nsubtitle: \"Fuente, diccionario de variables, control de calidad y reproducibilidad\"\n---\n\n\n\n## 1. Fuente y licencia {.unnumbered}\n\nLa base de trabajo es la publicada por la plataforma **PetFinder.my** en la competencia\n*PetFinder.my Adoption Prediction* de Kaggle (2019) [@kaggle2019petfinder], disponible también\ncomo registro independiente en Zenodo [@zenodo2019petfinder] y usada en la literatura\nposterior [@zadeh2022pet]. Los datos son de acceso público; los identificadores de los\nrescatistas (`RescuerID`) son seudónimos y no hay datos personales de adoptantes.\n\nEs una base de **datos secundarios**: ya existía, fue producida por otro actor y con otro\npropósito (una competencia de aprendizaje automático). Nuestro aporte metodológico consiste en\nenriquecerla y someterla a un protocolo de investigación explícito.\n\n## 2. Qué hay en la carpeta `data/` {.unnumbered}\n\n\n::: {.cell tbl-cap='Archivos que componen la fuente de datos'}\n::: {.cell-output-display}\n\n\n|Archivo o carpeta                    |Contenido                                                                | Tamaño|\n|:------------------------------------|:------------------------------------------------------------------------|------:|\n|data/train.csv                       |Anuncios originales (24 columnas)                                        |  NA MB|\n|data/train_sentiment                 |NA archivos JSON con el análisis de sentimiento por anuncio              |  NA MB|\n|data/train_metadata                  |NA archivos JSON con etiquetas, rostros y colores por imagen             |  NA MB|\n|data/petfinder_enriquecido_final.csv |Base enriquecida en texto plano (14.993 × 31)                            |  NA MB|\n|data/petfinder_enriquecido_final.rds |La misma base en formato R (más liviana y con los factores ya definidos) |  NA MB|\n\n\n:::\n:::\n\n\nLos archivos JSON no se analizan directamente en este sitio: se consolidan una sola vez en\n`data/petfinder_enriquecido_final.csv` mediante el script\n[`scripts/01_dataset_enriquecido.R`](https://github.com/JaredMijail/EDM_PetFInder/blob/main/scripts/01_dataset_enriquecido.R).\n\n## 3. Diccionario de variables {.unnumbered}\n\nLa unidad de análisis es el **anuncio de adopción** (clave `PetID`), no el animal ni el\nrescatista: un rescatista puede publicar varios animales y un animal tiene un solo anuncio.\nLas escalas de medición siguen la clasificación de Briones [-@briones2002].\n\n### 3.1 Variables originales del anuncio {.unnumbered}\n\n| Variable | Tipo en R | Escala | Descripción y valores |\n|:---------------|:-------------|:------------|:---------------------------------------------------------------------------------------|\n| `PetID` | carácter | Nominal | Identificador del anuncio; clave de unión con las demás fuentes |\n| `Type` | factor | Nominal | Especie: 1 = Perro, 2 = Gato |\n| `Name` | carácter | Nominal | Nombre del animal (vacío en algunos anuncios) |\n| `Age` | entero | Razón | Edad en meses |\n| `Breed1` | factor | Nominal | Raza principal |\n| `Breed2` | factor | Nominal | Raza secundaria; 0 = sin segunda raza |\n| `Gender` | factor | Nominal | 1 = Macho, 2 = Hembra, 3 = Mixto (varios animales en el anuncio) |\n| `Color1`, `Color2`, `Color3` | factor | Nominal | Colores del pelaje (1–7); 0 = no aplica |\n| `MaturitySize` | factor | Ordinal | 0 = no especificado, 1 = pequeño, 2 = mediano, 3 = grande, 4 = extra grande |\n| `FurLength` | factor | Ordinal | 0 = no especificado, 1 = corto, 2 = mediano, 3 = largo |\n| `Vaccinated` | factor | Nominal | 1 = sí, 2 = no, 3 = no está seguro |\n| `Dewormed` | factor | Nominal | Desparasitado: 1 = sí, 2 = no, 3 = no está seguro |\n| `Sterilized` | factor | Nominal | Esterilizado: 1 = sí, 2 = no, 3 = no está seguro |\n| `Health` | factor | Ordinal | 0 = no especificado, 1 = sano, 2 = lesión leve, 3 = lesión grave |\n| `Quantity` | entero | Razón | Número de animales incluidos en el anuncio (1–20) |\n| `Fee` | entero | Razón | Tarifa de adopción solicitada (ringgit malayo, MYR) |\n| `State` | factor | Nominal | Estado o territorio de Malasia donde está el animal |\n| `RescuerID` | carácter | Nominal | Identificador seudónimo de quien publica |\n| `VideoAmt` | entero | Razón | Número de videos en el anuncio |\n| `PhotoAmt` | entero | Razón | Número de fotografías en el anuncio |\n| `Description` | texto | — | Relato libre del rescatista sobre el animal (Malayo e inglés) |\n| `AdoptionSpeed` | factor | **Ordinal** | **Variable respuesta**: 0 = mismo día, 1 = 1–7 días, 2 = 8–30 días, 3 = 31–90 días, 4 = sin adopción tras 100 días |\n\n### 3.2 Variables construidas en el enriquecimiento {.unnumbered}\n\n| Variable | Tipo en R | Escala | Descripción y origen |\n|:----------------------|:-------------|:------------|:--------------------------------------------------------------------------------|\n| `sentiment_score` | numérico | Intervalo | Polaridad del relato, en [−1, 1]. Google Natural Language API [@googlenl2026] |\n| `sentiment_magnitude` | numérico | Razón | Intensidad emocional del relato (≥ 0). Google Natural Language API |\n| `total_labels` | entero | Razón | Etiquetas de contenido detectadas en las fotos del anuncio. Google Vision API [@googlevision2026] |\n| `total_faces` | entero | Razón | Rostros humanos detectados en las fotos del anuncio. Google Vision API |\n| `total_colors` | entero | Razón | Colores dominantes detectados en las fotos del anuncio. Google Vision API |\n| `desc_char_len` | entero | Razón | Número de caracteres del relato (cálculo propio) |\n| `desc_word_count` | entero | Razón | Número de palabras del relato (cálculo propio) |\n\n## 4. Control de calidad {.unnumbered}\n\n\n::: {.cell tbl-cap='Auditoría de la base enriquecida: faltantes, duplicados y valores extremos'}\n::: {.cell-output-display}\n\n\n|Verificación                                 |Resultado                                                                               |\n|:--------------------------------------------|:---------------------------------------------------------------------------------------|\n|Anuncios (filas)                             |14.993                                                                                  |\n|Variables (columnas)                         |31                                                                                      |\n|Identificadores PetID duplicados             |0                                                                                       |\n|Anuncios sin segunda raza (Breed2 = 0)       |10.762 (71.8 %)                                                                         |\n|Anuncios con video (VideoAmt > 0)            |574 (3.8 %)                                                                             |\n|Anuncios sin tarifa de adopción (Fee = 0)    |12.663 (84.5 %)                                                                         |\n|Anuncios con relato vacío (Description = '') |0                                                                                       |\n|Edad: mediana / máximo (meses)               |3 / 255                                                                                 |\n|Fotos: mediana / máximo                      |3 / 30                                                                                  |\n|Variables con faltantes                      |6 (Name, sentiment_score, sentiment_magnitude, total_labels, total_faces, total_colors) |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Variables con datos faltantes\n\n|Variable            | Faltantes| % faltantes|\n|:-------------------|---------:|-----------:|\n|Name                |      1257|         8,4|\n|sentiment_score     |       551|         3,7|\n|sentiment_magnitude |       551|         3,7|\n|total_labels        |       341|         2,3|\n|total_faces         |       341|         2,3|\n|total_colors        |       341|         2,3|\n\n\n:::\n:::\n\n\nLos faltantes son **informativos, no aleatorios**: un anuncio sin relato no genera puntaje de\nsentimiento, y un anuncio sin fotografía no genera anotaciones de imagen. Por eso el\nenriquecimiento trae tres variables con el mismo número de faltantes (los 341 anuncios sin\nfoto) y el sentimiento falta en los 551 anuncios con relato vacío. Este patrón hay que\ntratarlo explícitamente en el modelamiento (indicador de ausencia + imputación declarada), no\nborrando filas.\n\n## 5. Cómo se construyó la base {.unnumbered}\n\nEl script `scripts/01_dataset_enriquecido.R` ejecuta\nocho pasos, en el orden en que Briones [-@briones2002] propone el procesamiento de la\ninformación:\n\n\n::: {.cell tbl-cap='Pasos del procesamiento y su producto'}\n::: {.cell-output-display}\n\n\n| Paso |Operación                                                                           |Producto                                |\n|:----:|:-----------------------------------------------------------------------------------|:---------------------------------------|\n|  1   |Definir rutas relativas al proyecto (paquete here)                                  |Reproducibilidad en cualquier equipo    |\n|  2   |Leer el archivo principal train.csv                                                 |14 993 × 24                             |\n|  3   |Extraer el sentimiento de los JSON uno por uno y unirlos por PetID                  |sentiment_score, sentiment_magnitude    |\n|  4   |Extraer etiquetas, rostros y colores de los JSON de imagen y agregarlos por anuncio |total_labels, total_faces, total_colors |\n|  5   |Unir las tres fuentes por PetID (left_join)                                         |Base integrada                          |\n|  6   |Convertir las variables categóricas a factores con etiquetas legibles               |Variables interpretables                |\n|  7   |Calcular longitud del relato en caracteres y palabras                               |desc_char_len, desc_word_count          |\n|  8   |Diagnóstico de faltantes y exportación a CSV y RDS                                  |petfinder_enriquecido_final.csv / .rds  |\n\n\n:::\n:::\n\n\nLas claves de este procesamiento:\n\n* **Unión por clave única.** `PetID` identifica el anuncio; los JSON de imagen se llaman\n  `PetID-n.json`, así que se agregan con `sum()` por anuncio antes de unir. Un `left_join`\n  sobre la base original no agrega ni pierde filas: se verificó que el resultado sigue\n  teniendo 14 993 anuncios.\n* **Tolerancia a fallos.** Cada lectura de JSON va dentro de un `tryCatch`; un archivo\n  corrupto produce un faltante declarado, no la caída del proceso.\n* **Etiquetas legibles.** Los códigos numéricos del archivo original (1/2/3…) se convierten\n  a factores con etiquetas (`\"Yes\"`, `\"No\"`, `\"NotSure\"`), lo que evita errores de\n  interpretación en el análisis y en los gráficos.\n\n## 6. Reproducibilidad {.unnumbered}\n\n* Las dependencias de R están fijadas en `renv.lock`; se restauran con `renv::restore()`.\n* El sitio se construye con Quarto [@quarto2026]: `quarto render`.\n* Los resultados de los bloques de código quedan en caché (`_freeze`), de modo que el sitio se\n  puede renderizar sin tener los 550 MB de datos crudos.\n* Las figuras y tablas de estas páginas se calculan **en el momento de la construcción** a\n  partir de la base, no se transcriben a mano.\n\n## 7. Limitaciones de la fuente {.unnumbered}\n\n::: {.callout-important}\n## Lo que la base no permite afirmar\n1. **Cobertura geográfica.** Son anuncios de Malasia (2019). Las conclusiones describen esa\n   plataforma; su traslado a Colombia es una hipótesis, no un resultado.\n2. **Origen de la etiqueta.** `AdoptionSpeed` la registra el refugio o el rescatista, con\n   criterios de reporte que no controlamos; puede haber error de medición.\n3. **\"Sin adopción\" no es \"nunca adoptado\".** La categoría 4 significa \"no adoptado en 100\n   días\", es decir, es una observación censurada.\n4. **Selección.** Solo aparecen animales que llegaron a publicarse en la plataforma;\n   no es una muestra de la población de animales abandonados.\n5. **Anotaciones automáticas.** Sentimiento y etiquetas visuales provienen de modelos de\n   Google entrenados para otros fines; son medidas *proxy*, con su propio error.\n:::\n\nLas consecuencias de estas limitaciones para el diseño y para lo que se puede concluir se\ndesarrollan en la [Entrega 1](../entregas/entrega-1-metodologia.qmd#limitaciones).\n",
    "supporting": [
      "dataset_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}