{
  "hash": "f71566525fcd1c0bbc765881b1a2eb02",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Análisis exploratorio\"\nsubtitle: \"Entrega 1 — Análisis univariado del dataset PetFinder.my\"\nauthor: \"Jared Mijail Ramírez Escalante · María Paula Silva Capera\"\n---\n\n::: action-bar\n[Dataset y enriquecimiento](dataset.qmd){.btn-ghost} [Metodología](../proyecto/metodologia.qmd){.btn-ghost} <button class=\"btn-print\" onclick=\"window.print()\">Imprimir / Guardar como PDF</button>\n:::\n\nEsta entrega corresponde al **análisis univariado** de la base enriquecida: se describe cada variable **por separado** (distribución, tendencia central, dispersión, forma, valores atípicos y frecuencias, según su tipo). Por el alcance de esta entrega **no** se incluyen cruces entre variables, medidas de asociación, correlaciones, reducción de dimensionalidad ni modelos; esos análisis corresponden a las entregas siguientes.\n\nBase de trabajo: `data/petfinder_enriquecido_final.csv` (14 993 anuncios × 31 variables), descrita en la página de [Dataset y enriquecimiento](dataset.qmd). Todas las cifras de esta página se calculan al construir el sitio: no hay resultados transcritos a mano.\n\n## Análisis univariado {#univariado}\n\n### Análisis general {#general}\n\nAquí se describe la **estructura global** de la base. No se analiza variable por variable: eso se hace en las dos partes siguientes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\noptions(OutDec = \",\")   # separador decimal en español\nknitr::opts_chunk$set(fig.width = 4.6, fig.height = 3.3, dpi = 120, out.width = \"100%\")\n\ndatos <- readr::read_csv(\n  here::here(\"data\", \"petfinder_enriquecido_final.csv\"),\n  show_col_types = FALSE\n) |>\n  mutate(\n    Type          = factor(Type, levels = c(\"Dog\", \"Cat\"), labels = c(\"Perro\", \"Gato\")),\n    Gender        = factor(Gender, levels = c(\"Male\", \"Female\", \"Mixed\"),\n                           labels = c(\"Macho\", \"Hembra\", \"Mixto\")),\n    MaturitySize  = factor(MaturitySize, levels = c(\"Small\", \"Medium\", \"Large\", \"XLarge\"),\n                           labels = c(\"Pequeño\", \"Mediano\", \"Grande\", \"Extra grande\")),\n    FurLength     = factor(FurLength, levels = c(\"Short\", \"Medium\", \"Long\"),\n                           labels = c(\"Corto\", \"Mediano\", \"Largo\")),\n    Vaccinated    = factor(Vaccinated, levels = c(\"Yes\", \"No\", \"NotSure\"),\n                           labels = c(\"Sí\", \"No\", \"No está seguro\")),\n    Dewormed      = factor(Dewormed, levels = c(\"Yes\", \"No\", \"NotSure\"),\n                           labels = c(\"Sí\", \"No\", \"No está seguro\")),\n    Sterilized    = factor(Sterilized, levels = c(\"Yes\", \"No\", \"NotSure\"),\n                           labels = c(\"Sí\", \"No\", \"No está seguro\")),\n    Health        = factor(Health, levels = c(\"Healthy\", \"MinorInjury\", \"SeriousInjury\"),\n                           labels = c(\"Sano\", \"Lesión leve\", \"Lesión grave\")),\n    AdoptionSpeed = factor(AdoptionSpeed,\n                           levels = c(\"SameDay\", \"1-7d\", \"8-30d\", \"31-90d\", \"NoAdoption\"),\n                           labels = c(\"Mismo día\", \"1–7 días\", \"8–30 días\",\n                                      \"31–90 días\", \"Sin adopción\"))\n  )\n\nVARS_NUM <- c(\"Age\", \"Quantity\", \"Fee\", \"PhotoAmt\", \"VideoAmt\", \"sentiment_score\",\n              \"sentiment_magnitude\", \"total_labels\", \"total_faces\", \"total_colors\",\n              \"desc_char_len\", \"desc_word_count\")\nVARS_CAT <- c(\"Type\", \"Gender\", \"MaturitySize\", \"FurLength\", \"Vaccinated\", \"Dewormed\",\n              \"Sterilized\", \"Health\", \"AdoptionSpeed\", \"Color1\", \"Color2\", \"Color3\",\n              \"Breed1\", \"Breed2\", \"State\", \"Name\", \"Description\", \"PetID\", \"RescuerID\")\n\n# --- formateo de cifras en español ---\nfmt <- function(x, d = 2) {\n  x <- as.numeric(x)\n  if (all(abs(x - round(x)) < 1e-9)) {\n    return(format(round(x), big.mark = \".\", decimal.mark = \",\", scientific = FALSE))\n  }\n  format(round(x, d), big.mark = \".\", decimal.mark = \",\", nsmall = d, scientific = FALSE)\n}\nent <- function(x) format(as.integer(round(as.numeric(x))), big.mark = \".\", decimal.mark = \",\")\npct <- function(x, d = 1) gsub(\"\\\\.\", \",\", sprintf(paste0(\"%.\", d, \"f %%\"), x))\n\n# --- estadísticos ---\nmoda      <- function(x) { x <- x[!is.na(x)]; ux <- unique(x); ux[which.max(tabulate(match(x, ux)))] }\nasimetria <- function(x) { x <- x[!is.na(x)]; n <- length(x); m <- mean(x); s <- sd(x); n/((n-1)*(n-2))*sum(((x-m)/s)^3) }\ncurtosis  <- function(x) { x <- x[!is.na(x)]; n <- length(x); m <- mean(x); s <- sd(x)\n  n*(n+1)/((n-1)*(n-2)*(n-3))*sum(((x-m)/s)^4) - 3*(n-1)^2/((n-2)*(n-3)) }\n\nesc_num <- function(x) {\n  x <- as.numeric(x); v <- x[!is.na(x)]; q <- quantile(v, c(.25, .75)); iqr <- diff(q)\n  z <- (v - mean(v)) / sd(v); li <- q[1] - 1.5*iqr; ls <- q[2] + 1.5*iqr\n  list(n = length(v), na = sum(is.na(x)), media = mean(v), mediana = median(v), moda = as.numeric(moda(v)),\n       min = min(v), max = max(v), q1 = q[1], q3 = q[2], iqr = iqr, rango = max(v) - min(v),\n       var = var(v), sd = sd(v), cv = 100*sd(v)/mean(v), asim = asimetria(v), curt = curtosis(v),\n       out_iqr = sum(v < li | v > ls), pct_out_iqr = 100*mean(v < li | v > ls),\n       out_z = sum(abs(z) > 3), pct_out_z = 100*mean(abs(z) > 3), pct_ceros = 100*mean(v == 0),\n       unicos = length(unique(v)))\n}\n\nesc_cat <- function(x) {\n  v <- as.character(x); tb <- sort(table(v), decreasing = TRUE)\n  list(n = length(v), niveles = length(tb), moda = names(tb)[1], n_moda = as.integer(tb[1]),\n       pct_moda = 100*tb[1]/length(v), raras = sum(tb/length(v) < 0.01),\n       pct_raras = 100*sum(tb[tb/length(v) < 0.01])/length(v),\n       unicos = length(tb), unicidad = 100*length(tb)/length(v))\n}\n\nE <- lapply(setNames(VARS_NUM, VARS_NUM), function(v) esc_num(datos[[v]]))\nC <- lapply(setNames(VARS_CAT, VARS_CAT), function(v) esc_cat(datos[[v]]))\n\nlectura_asim <- function(a) if (abs(a) < 0.5) \"prácticamente simétrica\" else if (a >= 0.5) \"asimétrica positiva (cola a la derecha)\" else \"asimétrica negativa (cola a la izquierda)\"\nlectura_cv   <- function(cv) if (cv < 15) \"baja\" else if (cv < 30) \"moderada\" else if (cv < 60) \"alta\" else \"muy alta\"\n\n# --- tablas ---\ntabla_estadisticos <- function(x) {\n  s <- esc_num(x)\n  tibble::tibble(\n    `Estadístico` = c(\"Observaciones válidas\", \"Valores perdidos\", \"Media\", \"Mediana\", \"Moda\",\n                      \"Mínimo\", \"Máximo\", \"Primer cuartil (Q1)\", \"Tercer cuartil (Q3)\",\n                      \"Rango intercuartílico (IQR)\", \"Rango\", \"Varianza\", \"Desviación estándar\",\n                      \"Coeficiente de variación\", \"Asimetría\", \"Curtosis\"),\n    Valor = c(ent(s$n), ent(s$na), fmt(s$media), fmt(s$mediana), fmt(s$moda), fmt(s$min),\n              fmt(s$max), fmt(s$q1), fmt(s$q3), fmt(s$iqr), fmt(s$rango), fmt(s$var),\n              fmt(s$sd), pct(s$cv), fmt(s$asim, 3), fmt(s$curt, 3))\n  ) |> knitr::kable(align = c(\"l\", \"r\"))\n}\n\ntabla_atipicos <- function(x, k = 3) {\n  x <- as.numeric(x); v <- x[!is.na(x)]; q <- quantile(v, c(.25, .75)); iqr <- diff(q)\n  z <- (v - mean(v))/sd(v); li <- q[1] - 1.5*iqr; ls <- q[2] + 1.5*iqr\n  tibble::tibble(\n    Criterio = c(\"Regla de 1,5 × IQR\", paste0(\"Puntaje z (|z| > \", k, \")\")),\n    `Límite inferior` = c(fmt(li), fmt(mean(v) - k*sd(v))),\n    `Límite superior` = c(fmt(ls), fmt(mean(v) + k*sd(v))),\n    Atípicos = c(ent(sum(v < li | v > ls)), ent(sum(abs(z) > k))),\n    `% del total` = c(pct(100*mean(v < li | v > ls)), pct(100*mean(abs(z) > k)))\n  ) |> knitr::kable(align = c(\"l\", \"r\", \"r\", \"r\", \"r\"))\n}\n\ntabla_frecuencias <- function(x, etiqueta = \"Categoría\", n_top = 10) {\n  v <- as.character(x); tb <- sort(table(v), decreasing = TRUE); n <- length(tb); tot <- sum(tb)\n  if (n > n_top) {\n    tab <- tibble::tibble(\n      Categoría = c(names(tb)[1:(n_top - 1)], sprintf(\"Otras (%d categorías)\", n - n_top + 1)),\n      Frecuencia = c(as.integer(tb[1:(n_top - 1)]), tot - sum(tb[1:(n_top - 1)])))\n  } else {\n    tab <- tibble::tibble(Categoría = names(tb), Frecuencia = as.integer(tb))\n  }\n  tab |>\n    mutate(`Frecuencia relativa` = 100*Frecuencia/sum(Frecuencia),\n           `Frecuencia acumulada` = cumsum(`Frecuencia relativa`)) |>\n    mutate(Frecuencia = ent(Frecuencia),\n           `Frecuencia relativa` = pct(`Frecuencia relativa`),\n           `Frecuencia acumulada` = pct(`Frecuencia acumulada`)) |>\n    knitr::kable(col.names = c(etiqueta, \"Frecuencia absoluta\", \"Frecuencia relativa\",\n                               \"Frecuencia acumulada\"), align = c(\"l\", \"r\", \"r\", \"r\"))\n}\n\ntabla_cardinalidad <- function(x) {\n  v <- as.character(x)\n  tibble::tibble(\n    Verificación = c(\"Observaciones\", \"Valores perdidos\", \"Categorías distintas\",\n                     \"Proporción de valores distintos\", \"Categoría más frecuente\",\n                     \"Frecuencia de la moda\"),\n    Resultado = c(ent(length(v)), ent(sum(is.na(x))), ent(length(unique(v))),\n                  pct(100*length(unique(v))/length(v)),\n                  names(sort(table(v), decreasing = TRUE))[1],\n                  pct(100*max(table(v))/length(v)))\n  ) |> knitr::kable(align = c(\"l\", \"r\"))\n}\n\n# --- gráficos ---\ntema_u <- function() {\n  theme_minimal(base_size = 11.5) +\n    theme(plot.background = element_rect(fill = \"white\", colour = NA),\n          panel.background = element_rect(fill = \"white\", colour = NA),\n          plot.title = element_text(colour = \"#1a3a5c\", face = \"bold\", size = 11.5),\n          axis.title = element_text(colour = \"#4b5563\", size = 10),\n          panel.grid.minor = element_blank())\n}\n\ngraficos_cuanti <- function(x, etiqueta, tipo = c(\"continuo\", \"conteo\")) {\n  tipo <- match.arg(tipo)\n  d <- tibble::tibble(v = as.numeric(x))\n  p1 <- ggplot(d, aes(v)) +\n    geom_histogram(bins = 30, fill = \"#2e7d9a\", colour = \"white\", linewidth = 0.2) +\n    labs(title = \"Histograma\", x = etiqueta, y = \"Frecuencia\") + tema_u()\n  p2 <- ggplot(d, aes(y = v)) +\n    geom_boxplot(\n      fill = \"#d97706\", \n      width = 0.32, \n      outlier.shape = 1,       \n      outlier.colour = \"black\",  \n      outlier.alpha = 1,       \n      outlier.size = 1.5        \n    ) +\n    labs(title = \"Diagrama de caja\", x = NULL, y = etiqueta) +\n    tema_u() +\n    theme(\n      axis.text.x = element_blank(),\n      aspect.ratio = 1.8\n    )\n  p3 <- ggplot(d, aes(v)) +\n    geom_density(fill = \"#0f766e\", alpha = 0.35, colour = \"#0f766e\") +\n    labs(title = \"Densidad\", x = etiqueta, y = \"Densidad\") + tema_u()\n  p4 <- if (tipo == \"continuo\") {\n    ggplot(d, aes(sample = v)) +\n      stat_qq(colour = \"#1a3a5c\", alpha = 0.4, size = 0.8) +\n      stat_qq_line(colour = \"#d97706\") +\n      labs(title = \"QQ-plot (referencia normal)\", x = \"Cuantiles teóricos\", y = \"Cuantiles muestrales\") + tema_u()\n  } else {\n    d |> count(v) |> slice_max(n, n = 8) |> mutate(v = factor(v)) |>\n      ggplot(aes(x = v, y = n)) + geom_col(fill = \"#1a3a5c\") +\n      labs(title = \"Valores más frecuentes\", x = etiqueta, y = \"Frecuencia\") + tema_u()\n  }\n  for (p in list(p1, p2, p3, p4)) print(p)\n  invisible(NULL)\n}\n\ngraficos_cuali <- function(x, etiqueta, pastel = FALSE, n_top = 10) {\n  v <- as.character(x); tb <- sort(table(v), decreasing = TRUE); n <- length(tb); tot <- sum(tb)\n  d <- if (n > n_top) {\n    tibble::tibble(cat = c(names(tb)[1:(n_top - 1)], sprintf(\"Otras (%d)\", n - n_top + 1)),\n                   n = c(as.integer(tb[1:(n_top - 1)]), tot - sum(tb[1:(n_top - 1)])))\n  } else tibble::tibble(cat = names(tb), n = as.integer(tb))\n  d <- d |> mutate(cat = factor(cat, levels = rev(cat)),\n                   pct = 100*n/sum(n))\n  p1 <- ggplot(d, aes(x = pct, y = cat)) +\n    geom_col(fill = \"#2e7d9a\", width = 0.7) +\n    geom_text(aes(label = sprintf(\"%.1f %%\", pct)), hjust = -0.15, size = 3, colour = \"#1f2937\") +\n    scale_x_continuous(expand = expansion(mult = c(0, 0.22))) +\n    labs(title = \"Distribución de frecuencias\", x = \"Porcentaje de anuncios\", y = etiqueta) + tema_u()\n  if (!pastel) { print(p1); return(invisible(NULL)) }\n  p2 <- ggplot(d, aes(x = \"\", y = n, fill = cat)) +\n    geom_col(width = 1, colour = \"white\") + coord_polar(\"y\") +\n    labs(title = \"Composición porcentual\", x = NULL, y = NULL) +\n    theme_minimal(base_size = 11.5) +\n    theme(plot.background = element_rect(fill = \"white\", colour = NA),\n          plot.title = element_text(colour = \"#1a3a5c\", face = \"bold\", size = 11.5),\n          legend.title = element_blank(), legend.text = element_text(size = 9),\n          legend.position = \"right\", axis.text = element_blank(), panel.grid = element_blank())\n  print(p1); print(p2)\n  invisible(NULL)\n}\n```\n:::\n\n\n\n::: {.cell tbl-cap='Dimensión y estructura general de la base'}\n\n```{.r .cell-code}\ntibble::tibble(\n  Aspecto = c(\"Unidades de análisis\", \"Variables\", \"Celdas de datos\", \"Valores perdidos\",\n              \"Porcentaje de celdas completas\", \"Filas duplicadas\",\n              \"Identificadores duplicados (PetID)\", \"Tamaño en memoria\",\n              \"Variables cuantitativas\", \"Variables cualitativas\"),\n  Resultado = c(paste(ent(nrow(datos)), \"anuncios\"),\n                paste(ncol(datos), \"variables\"),\n                ent(nrow(datos) * ncol(datos)),\n                sprintf(\"%s (%.2f %%)\", ent(sum(is.na(datos))), 100 * mean(is.na(datos))),\n                pct(100 - 100 * mean(is.na(datos)), 2),\n                ent(sum(duplicated(datos))),\n                ent(sum(duplicated(datos$PetID))),\n                format(object.size(datos), units = \"MB\"),\n                sprintf(\"%d (%.1f %%)\", length(VARS_NUM), 100 * length(VARS_NUM) / ncol(datos)),\n                sprintf(\"%d (%.1f %%)\", length(VARS_CAT), 100 * length(VARS_CAT) / ncol(datos)))\n) |>\n  knitr::kable(align = c(\"l\", \"l\"))\n```\n\n::: {.cell-output-display}\n\n\n|Aspecto                            |Resultado       |\n|:----------------------------------|:---------------|\n|Unidades de análisis               |14.993 anuncios |\n|Variables                          |31 variables    |\n|Celdas de datos                    |464.783         |\n|Valores perdidos                   |3.382 (0.73 %)  |\n|Porcentaje de celdas completas     |99,27 %         |\n|Filas duplicadas                   |0               |\n|Identificadores duplicados (PetID) |0               |\n|Tamaño en memoria                  |10,5 Mb         |\n|Variables cuantitativas            |12 (38.7 %)     |\n|Variables cualitativas             |19 (61.3 %)     |\n\n\n:::\n:::\n\n\n**Tipos de variables.** Las 31 variables se clasifican por su naturaleza y su escala de medición. La columna *Fuente* distingue las variables originales de la competencia de las que se construyeron en el enriquecimiento (texto e imagen).\n\n\n::: {.cell tbl-cap='Clasificación de las 31 variables por tipo, escala y origen'}\n\n```{.r .cell-code}\nclasificacion <- tibble::tribble(\n  ~Variable, ~`Tipo en R`, ~Grupo, ~Escala, ~Fuente,\n  \"PetID\",              \"carácter\",  \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"Name\",               \"carácter\",  \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"Type\",               \"factor\",    \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"Breed1\",             \"factor\",    \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"Breed2\",             \"factor\",    \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"Gender\",             \"factor\",    \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"Color1\",             \"factor\",    \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"Color2\",             \"factor\",    \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"Color3\",             \"factor\",    \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"Vaccinated\",         \"factor\",    \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"Dewormed\",           \"factor\",    \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"Sterilized\",         \"factor\",    \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"State\",              \"factor\",    \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"RescuerID\",          \"carácter\",  \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"Description\",        \"texto\",     \"Cualitativa nominal\",   \"Nominal\",   \"Original\",\n  \"MaturitySize\",       \"factor\",    \"Cualitativa ordinal\",   \"Ordinal\",   \"Original\",\n  \"FurLength\",          \"factor\",    \"Cualitativa ordinal\",   \"Ordinal\",   \"Original\",\n  \"Health\",             \"factor\",    \"Cualitativa ordinal\",   \"Ordinal\",   \"Original\",\n  \"AdoptionSpeed\",      \"factor\",    \"Cualitativa ordinal\",   \"Ordinal\",   \"Original\",\n  \"Age\",                \"entero\",    \"Cuantitativa discreta\", \"De razón\",  \"Original\",\n  \"Quantity\",           \"entero\",    \"Cuantitativa discreta\", \"De razón\",  \"Original\",\n  \"Fee\",                \"entero\",    \"Cuantitativa discreta\", \"De razón\",  \"Original\",\n  \"VideoAmt\",           \"entero\",    \"Cuantitativa discreta\", \"De razón\",  \"Original\",\n  \"PhotoAmt\",           \"entero\",    \"Cuantitativa discreta\", \"De razón\",  \"Original\",\n  \"sentiment_score\",    \"numérico\",  \"Cuantitativa continua\", \"De intervalo\", \"Enriquecimiento (texto)\",\n  \"sentiment_magnitude\",\"numérico\",  \"Cuantitativa continua\", \"De razón\",  \"Enriquecimiento (texto)\",\n  \"total_labels\",       \"entero\",    \"Cuantitativa discreta\", \"De razón\",  \"Enriquecimiento (imagen)\",\n  \"total_faces\",        \"entero\",    \"Cuantitativa discreta\", \"De razón\",  \"Enriquecimiento (imagen)\",\n  \"total_colors\",       \"entero\",    \"Cuantitativa discreta\", \"De razón\",  \"Enriquecimiento (imagen)\",\n  \"desc_char_len\",      \"entero\",    \"Cuantitativa discreta\", \"De razón\",  \"Derivada del texto\",\n  \"desc_word_count\",    \"entero\",    \"Cuantitativa discreta\", \"De razón\",  \"Derivada del texto\"\n) |>\n  dplyr::arrange(Grupo, Variable)\n\nclasificacion |> knitr::kable(align = c(\"l\", \"l\", \"l\", \"l\", \"l\"))\n```\n\n::: {.cell-output-display}\n\n\n|Variable            |Tipo en R |Grupo                 |Escala       |Fuente                   |\n|:-------------------|:---------|:---------------------|:------------|:------------------------|\n|Breed1              |factor    |Cualitativa nominal   |Nominal      |Original                 |\n|Breed2              |factor    |Cualitativa nominal   |Nominal      |Original                 |\n|Color1              |factor    |Cualitativa nominal   |Nominal      |Original                 |\n|Color2              |factor    |Cualitativa nominal   |Nominal      |Original                 |\n|Color3              |factor    |Cualitativa nominal   |Nominal      |Original                 |\n|Description         |texto     |Cualitativa nominal   |Nominal      |Original                 |\n|Dewormed            |factor    |Cualitativa nominal   |Nominal      |Original                 |\n|Gender              |factor    |Cualitativa nominal   |Nominal      |Original                 |\n|Name                |carácter  |Cualitativa nominal   |Nominal      |Original                 |\n|PetID               |carácter  |Cualitativa nominal   |Nominal      |Original                 |\n|RescuerID           |carácter  |Cualitativa nominal   |Nominal      |Original                 |\n|State               |factor    |Cualitativa nominal   |Nominal      |Original                 |\n|Sterilized          |factor    |Cualitativa nominal   |Nominal      |Original                 |\n|Type                |factor    |Cualitativa nominal   |Nominal      |Original                 |\n|Vaccinated          |factor    |Cualitativa nominal   |Nominal      |Original                 |\n|AdoptionSpeed       |factor    |Cualitativa ordinal   |Ordinal      |Original                 |\n|FurLength           |factor    |Cualitativa ordinal   |Ordinal      |Original                 |\n|Health              |factor    |Cualitativa ordinal   |Ordinal      |Original                 |\n|MaturitySize        |factor    |Cualitativa ordinal   |Ordinal      |Original                 |\n|sentiment_magnitude |numérico  |Cuantitativa continua |De razón     |Enriquecimiento (texto)  |\n|sentiment_score     |numérico  |Cuantitativa continua |De intervalo |Enriquecimiento (texto)  |\n|Age                 |entero    |Cuantitativa discreta |De razón     |Original                 |\n|Fee                 |entero    |Cuantitativa discreta |De razón     |Original                 |\n|PhotoAmt            |entero    |Cuantitativa discreta |De razón     |Original                 |\n|Quantity            |entero    |Cuantitativa discreta |De razón     |Original                 |\n|VideoAmt            |entero    |Cuantitativa discreta |De razón     |Original                 |\n|desc_char_len       |entero    |Cuantitativa discreta |De razón     |Derivada del texto       |\n|desc_word_count     |entero    |Cuantitativa discreta |De razón     |Derivada del texto       |\n|total_colors        |entero    |Cuantitativa discreta |De razón     |Enriquecimiento (imagen) |\n|total_faces         |entero    |Cuantitativa discreta |De razón     |Enriquecimiento (imagen) |\n|total_labels        |entero    |Cuantitativa discreta |De razón     |Enriquecimiento (imagen) |\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![Número de variables por tipo](analisis-exploratorio_files/figure-html/general-tipos-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Composición porcentual por tipo de variable](analisis-exploratorio_files/figure-html/general-tipos-2.png){width=100%}\n:::\n:::\n\n\n**Valores perdidos.** Cinco variables presentan datos faltantes y todas pertenecen al enriquecimiento: el nombre del animal (1 257 casos), las dos variables de sentimiento (551 cada una) y las tres variables derivadas de la imagen (341 cada una, los anuncios sin fotografía).\n\n\n::: {.cell tbl-cap='Valores perdidos por variable'}\n\n```{.r .cell-code}\ntibble::tibble(Variable = names(datos), Perdidos = as.integer(colSums(is.na(datos)))) |>\n  dplyr::filter(Perdidos > 0) |>\n  dplyr::mutate(`% de las filas` = pct(100 * Perdidos / nrow(datos))) |>\n  dplyr::arrange(dplyr::desc(Perdidos)) |>\n  dplyr::mutate(Perdidos = ent(Perdidos)) |>\n  knitr::kable(col.names = c(\"Variable\", \"Valores perdidos\", \"% de las filas\"),\n               align = c(\"l\", \"r\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\n|Variable            | Valores perdidos| % de las filas|\n|:-------------------|----------------:|--------------:|\n|Name                |            1.257|          8,4 %|\n|sentiment_score     |              551|          3,7 %|\n|sentiment_magnitude |              551|          3,7 %|\n|total_labels        |              341|          2,3 %|\n|total_faces         |              341|          2,3 %|\n|total_colors        |              341|          2,3 %|\n\n\n:::\n:::\n\n\n**Duplicados.** No hay filas repetidas ni identificadores de anuncio repetidos: la base es un censo de anuncios únicos, lo que se verificó con `duplicated()` sobre las filas y sobre `PetID`.\n\n**Resumen global de las variables cuantitativas.** Una vista de conjunto antes de entrar variable por variable (la lectura detallada de cada una está en el análisis cuantitativo).\n\n\n::: {.cell tbl-cap='Resumen global de las 12 variables cuantitativas'}\n\n```{.r .cell-code}\npurrr::map_dfr(VARS_NUM, function(v) {\n  s <- E[[v]]\n  tibble::tibble(Variable = v, `n válidos` = ent(s$n), Perdidos = ent(s$na),\n                 Mínimo = fmt(s$min), `Q1` = fmt(s$q1), Media = fmt(s$media),\n                 Mediana = fmt(s$mediana), `Q3` = fmt(s$q3), Máximo = fmt(s$max),\n                 `Desv. est.` = fmt(s$sd), CV = pct(s$cv), Asimetría = fmt(s$asim, 2))\n}) |>\n  knitr::kable(align = c(\"l\", rep(\"r\", 11)))\n```\n\n::: {.cell-output-display}\n\n\n|Variable            | n válidos| Perdidos| Mínimo|   Q1|  Media| Mediana|   Q3| Máximo| Desv. est.|      CV| Asimetría|\n|:-------------------|---------:|--------:|------:|----:|------:|-------:|----:|------:|----------:|-------:|---------:|\n|Age                 |    14.993|        0|      0|    2|  10,45|       3|   12|    255|      18,16| 173,7 %|      3,76|\n|Quantity            |    14.993|        0|      1|    1|   1,58|       1|    1|     20|       1,47|  93,4 %|      4,60|\n|Fee                 |    14.993|        0|      0|    0|  21,26|       0|    0|  3.000|      78,41| 368,8 %|      8,92|\n|PhotoAmt            |    14.993|        0|      0|    2|   3,89|       3|    5|     30|       3,49|  89,7 %|      2,86|\n|VideoAmt            |    14.993|        0|      0|    0|   0,06|       0|    0|      8|       0,35| 609,9 %|      9,46|\n|sentiment_score     |    14.442|      551|  -0,90| 0,10|   0,28|    0,30| 0,40|   0,90|       0,28|  98,5 %|      0,23|\n|sentiment_magnitude |    14.442|      551|      0| 0,80|   2,13|    1,60| 2,80|     32|       2,04|  95,7 %|      2,91|\n|total_labels        |    14.652|      341|      1|   18|  37,28|      30|   48|    299|      32,62|  87,5 %|      2,90|\n|total_faces         |    14.652|      341|      0|    0|   0,05|       0|    0|      6|       0,29| 599,6 %|      8,44|\n|total_colors        |    14.652|      341|      6|   20|  39,72|      30|   50|    300|      34,70|  87,4 %|      2,91|\n|desc_char_len       |    14.993|        0|      1|  117| 339,31|     238|  431|  6.664|     373,37| 110,0 %|      4,00|\n|desc_word_count     |    14.993|        0|      1|   21|  62,95|      44|   81|  1.257|      69,30| 110,1 %|      3,91|\n\n\n:::\n:::\n\n\n**Lectura del análisis general.** La base tiene 14.993 unidades de análisis (los anuncios), 31 variables y 464.783 celdas, de las cuales se pierde el 0,73 %; ese porcentaje es bajo y está concentrado en cinco variables del enriquecimiento, así que un análisis univariado por variable puede hacerse sin imputaciones. Los 0 duplicados de fila y de identificador confirman que no hay anuncios repetidos. En cuanto a la composición, hay 12 variables cuantitativas (39 % del total) y 19 cualitativas (61 %), de modo que el análisis descriptivo tiene una parte cuantitativa y una cualitativa de tamaño comparable. Dos advertencias que se retoman más adelante: hay variables **casi constantes** (`Health`, `total_faces`, `VideoAmt`) y variables **de alta cardinalidad** (`Breed1`, `State`, `Name`, `Description`), que exigen tratamientos distintos de las tablas de frecuencia convencionales.\n\n### Análisis cuantitativo {#cuantitativo}\n\nSe analizan las 12 variables cuantitativas. Para cada una se reportan: tamaño de la muestra y valores perdidos; tendencia central (media, mediana y moda); posición (mínimo, máximo y cuartiles); dispersión (rango, IQR, varianza, desviación estándar y coeficiente de variación); forma (asimetría y curtosis) y detección de valores atípicos con dos criterios (regla de 1,5 × IQR y puntaje z con \\|z\\| \\> 3). La asimetría y la curtosis usan los estimadores muestrales tipo 2 de `e1071`, de modo que la curtosis es *exceso* respecto de la normal (0 = normal). Para las variables de **conteo** el cuarto panel muestra los valores más frecuentes en lugar del QQ-plot, porque la referencia normal no aplica a ese tipo de datos.\n\n#### `Age` — Edad {.unnumbered}\n\n\n::: {.cell tbl-cap='Estadísticos descriptivos — Edad (meses)'}\n\n```{.r .cell-code}\ntabla_estadisticos(datos$Age)\n```\n\n::: {.cell-output-display}\n\n\n|Estadístico                 |   Valor|\n|:---------------------------|-------:|\n|Observaciones válidas       |  14.993|\n|Valores perdidos            |       0|\n|Media                       |   10,45|\n|Mediana                     |       3|\n|Moda                        |       2|\n|Mínimo                      |       0|\n|Máximo                      |     255|\n|Primer cuartil (Q1)         |       2|\n|Tercer cuartil (Q3)         |      12|\n|Rango intercuartílico (IQR) |      10|\n|Rango                       |     255|\n|Varianza                    |  329,63|\n|Desviación estándar         |   18,16|\n|Coeficiente de variación    | 173,7 %|\n|Asimetría                   |   3,763|\n|Curtosis                    |  20,772|\n\n\n:::\n:::\n\n\n\n::: {.cell tbl-cap='Detección de valores atípicos — Edad (meses)'}\n\n```{.r .cell-code}\ntabla_atipicos(datos$Age)\n```\n\n::: {.cell-output-display}\n\n\n|Criterio                      | Límite inferior| Límite superior| Atípicos| % del total|\n|:-----------------------------|---------------:|---------------:|--------:|-----------:|\n|Regla de 1,5 × IQR            |             -13|              27|    1.501|      10,0 %|\n|Puntaje z (&#124;z&#124; > 3) |          -44,02|           64,92|      378|       2,5 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuanti(datos$Age, \"Edad (meses)\", tipo = \"conteo\")\n```\n\n::: {.cell-output-display}\n![Histograma de edad](analisis-exploratorio_files/figure-html/graf-Age-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Diagrama de caja de edad](analisis-exploratorio_files/figure-html/graf-Age-2.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Gráfico de densidad de edad](analisis-exploratorio_files/figure-html/graf-Age-3.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Valores más frecuentes de edad](analisis-exploratorio_files/figure-html/graf-Age-4.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** La edad se concentra en animales muy jóvenes: el 68,1 % de los anuncios corresponde a animales de seis meses o menos, y el 50 % central de la distribución está entre 2 y 12 meses. La distribución es **asimétrica positiva (cola a la derecha)** (asimetría = 3,76; curtosis = 20,77), con una media (10,45 meses) que casi cuadruplica la mediana (3 meses) porque la cola derecha la estiran los animales adultos: 10,3 % de los anuncios supera los dos años y el máximo es de 255 meses (21,2 años). El coeficiente de variación (173,7 %) es **muy alto**, señal de gran heterogeneidad. La regla de 1,5 × IQR marca 1.501 atípicos (10,0 %), todos por la cola alta. **Lectura:** la base está dominada por cachorros y animales jóvenes; los casos de animales mayores son reales, no errores, por lo que en el modelamiento la edad conviene tratarla en escala logarítmica o por tramos de edad.\n\n#### `Quantity` — Cantidad de animales en el anuncio {.unnumbered}\n\n\n::: {.cell tbl-cap='Estadísticos descriptivos — Cantidad de animales en el anuncio (animales)'}\n\n```{.r .cell-code}\ntabla_estadisticos(datos$Quantity)\n```\n\n::: {.cell-output-display}\n\n\n|Estadístico                 |  Valor|\n|:---------------------------|------:|\n|Observaciones válidas       | 14.993|\n|Valores perdidos            |      0|\n|Media                       |   1,58|\n|Mediana                     |      1|\n|Moda                        |      1|\n|Mínimo                      |      1|\n|Máximo                      |     20|\n|Primer cuartil (Q1)         |      1|\n|Tercer cuartil (Q3)         |      1|\n|Rango intercuartílico (IQR) |      0|\n|Rango                       |     19|\n|Varianza                    |   2,17|\n|Desviación estándar         |   1,47|\n|Coeficiente de variación    | 93,4 %|\n|Asimetría                   |  4,600|\n|Curtosis                    | 34,087|\n\n\n:::\n:::\n\n\n\n::: {.cell tbl-cap='Detección de valores atípicos — Cantidad de animales en el anuncio (animales)'}\n\n```{.r .cell-code}\ntabla_atipicos(datos$Quantity)\n```\n\n::: {.cell-output-display}\n\n\n|Criterio                      | Límite inferior| Límite superior| Atípicos| % del total|\n|:-----------------------------|---------------:|---------------:|--------:|-----------:|\n|Regla de 1,5 × IQR            |               1|               1|    3.428|      22,9 %|\n|Puntaje z (&#124;z&#124; > 3) |           -2,84|            5,99|      416|       2,8 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuanti(datos$Quantity, \"Animales en el anuncio\", tipo = \"conteo\")\n```\n\n::: {.cell-output-display}\n![Histograma de cantidad de animales en el anuncio](analisis-exploratorio_files/figure-html/graf-Quantity-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Diagrama de caja de cantidad de animales en el anuncio](analisis-exploratorio_files/figure-html/graf-Quantity-2.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Gráfico de densidad de cantidad de animales en el anuncio](analisis-exploratorio_files/figure-html/graf-Quantity-3.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Valores más frecuentes de cantidad de animales en el anuncio](analisis-exploratorio_files/figure-html/graf-Quantity-4.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** La variable es **esencialmente binaria**: el 77,1 % de los anuncios describe un solo animal, y los anuncios con más de uno son poco frecuentes (2 animales, 9,5 %; 3 o más, 13,4 %). Como el IQR es exactamente 0 (Q1 = Q3 = 1), la regla de 1,5 × IQR marca como atípico **cualquier** valor distinto de 1, lo que explica los 3.428 «atípicos» (22,9 %): no son errores, sino la consecuencia esperable de una distribución con el 50 % de los datos en un único valor. El criterio del puntaje z es más razonable aquí y detecta 416 anuncios (2,8 %), que corresponden a los grupos grandes (hasta 20 animales). **Lectura:** conviene usarla como variable binaria (un animal vs. varios) o por tramos; su máximo refleja anuncios de refugios que publican camadas completas.\n\n#### `Fee` — Tarifa de adopción {.unnumbered}\n\n\n::: {.cell tbl-cap='Estadísticos descriptivos — Tarifa de adopción (ringgit malayo (MYR))'}\n\n```{.r .cell-code}\ntabla_estadisticos(datos$Fee)\n```\n\n::: {.cell-output-display}\n\n\n|Estadístico                 |    Valor|\n|:---------------------------|--------:|\n|Observaciones válidas       |   14.993|\n|Valores perdidos            |        0|\n|Media                       |    21,26|\n|Mediana                     |        0|\n|Moda                        |        0|\n|Mínimo                      |        0|\n|Máximo                      |    3.000|\n|Primer cuartil (Q1)         |        0|\n|Tercer cuartil (Q3)         |        0|\n|Rango intercuartílico (IQR) |        0|\n|Rango                       |    3.000|\n|Varianza                    | 6.148,84|\n|Desviación estándar         |    78,41|\n|Coeficiente de variación    |  368,8 %|\n|Asimetría                   |    8,921|\n|Curtosis                    |  191,701|\n\n\n:::\n:::\n\n\n\n::: {.cell tbl-cap='Detección de valores atípicos — Tarifa de adopción (ringgit malayo (MYR))'}\n\n```{.r .cell-code}\ntabla_atipicos(datos$Fee)\n```\n\n::: {.cell-output-display}\n\n\n|Criterio                      | Límite inferior| Límite superior| Atípicos| % del total|\n|:-----------------------------|---------------:|---------------:|--------:|-----------:|\n|Regla de 1,5 × IQR            |               0|               0|    2.330|      15,5 %|\n|Puntaje z (&#124;z&#124; > 3) |         -213,98|          256,50|      326|       2,2 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuanti(datos$Fee, \"Tarifa (MYR)\", tipo = \"conteo\")\n```\n\n::: {.cell-output-display}\n![Histograma de tarifa de adopción](analisis-exploratorio_files/figure-html/graf-Fee-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Diagrama de caja de tarifa de adopción](analisis-exploratorio_files/figure-html/graf-Fee-2.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Gráfico de densidad de tarifa de adopción](analisis-exploratorio_files/figure-html/graf-Fee-3.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Valores más frecuentes de tarifa de adopción](analisis-exploratorio_files/figure-html/graf-Fee-4.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Es una variable **de dos regímenes**: el 84,5 % de los anuncios no cobra tarifa (mediana = Q1 = Q3 = 0), mientras que el 15,5 % restante sí lo hace y, entre esos casos, la mediana es de 100 MYR. Esa mezcla produce la asimetría y curtosis más extremas de la base (asimetría = 8,92, curtosis = 191,7), una media (21,26 MYR) muy superior a la mediana (0 MYR) y un máximo de 3.000 MYR. El coeficiente de variación (368,8 %) es el más alto entre las variables cuantitativas. **Lectura:** la tarifa debe analizarse como variable mixta (indicador de «¿cobra?» más el monto cuando cobra); tratada como continua, sus medidas de tendencia central son engañosas porque el 0 domina la distribución.\n\n#### `PhotoAmt` — Número de fotografías {.unnumbered}\n\n\n::: {.cell tbl-cap='Estadísticos descriptivos — Número de fotografías (fotos)'}\n\n```{.r .cell-code}\ntabla_estadisticos(datos$PhotoAmt)\n```\n\n::: {.cell-output-display}\n\n\n|Estadístico                 |  Valor|\n|:---------------------------|------:|\n|Observaciones válidas       | 14.993|\n|Valores perdidos            |      0|\n|Media                       |   3,89|\n|Mediana                     |      3|\n|Moda                        |      1|\n|Mínimo                      |      0|\n|Máximo                      |     30|\n|Primer cuartil (Q1)         |      2|\n|Tercer cuartil (Q3)         |      5|\n|Rango intercuartílico (IQR) |      3|\n|Rango                       |     30|\n|Varianza                    |  12,16|\n|Desviación estándar         |   3,49|\n|Coeficiente de variación    | 89,7 %|\n|Asimetría                   |  2,861|\n|Curtosis                    | 12,646|\n\n\n:::\n:::\n\n\n\n::: {.cell tbl-cap='Detección de valores atípicos — Número de fotografías (fotos)'}\n\n```{.r .cell-code}\ntabla_atipicos(datos$PhotoAmt)\n```\n\n::: {.cell-output-display}\n\n\n|Criterio                      | Límite inferior| Límite superior| Atípicos| % del total|\n|:-----------------------------|---------------:|---------------:|--------:|-----------:|\n|Regla de 1,5 × IQR            |           -2,50|            9,50|      922|       6,1 %|\n|Puntaje z (&#124;z&#124; > 3) |           -6,57|           14,35|      287|       1,9 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuanti(datos$PhotoAmt, \"Fotografías\", tipo = \"conteo\")\n```\n\n::: {.cell-output-display}\n![Histograma de número de fotografías](analisis-exploratorio_files/figure-html/graf-PhotoAmt-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Diagrama de caja de número de fotografías](analisis-exploratorio_files/figure-html/graf-PhotoAmt-2.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Gráfico de densidad de número de fotografías](analisis-exploratorio_files/figure-html/graf-PhotoAmt-3.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Valores más frecuentes de número de fotografías](analisis-exploratorio_files/figure-html/graf-PhotoAmt-4.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** El número de fotos es una variable discreta con moda en 1 foto ( de los anuncios), mediana 3 y media 3,89; el 2,3 % de los anuncios no tiene ninguna foto y el máximo es de 30. La distribución es **asimétrica positiva (cola a la derecha)** con curtosis 12,65, y la regla de 1,5 × IQR detecta 922 anuncios con muchas fotos (6,1 %), que son casos legítimos de rescatistas muy documentados. **Lectura:** la mayoría de los anuncios tiene entre 2 y 5 fotos; los anuncios sin fotos merecen seguimiento porque su ficha está incompleta.\n\n#### `VideoAmt` — Número de videos {.unnumbered}\n\n\n::: {.cell tbl-cap='Estadísticos descriptivos — Número de videos (videos)'}\n\n```{.r .cell-code}\ntabla_estadisticos(datos$VideoAmt)\n```\n\n::: {.cell-output-display}\n\n\n|Estadístico                 |   Valor|\n|:---------------------------|-------:|\n|Observaciones válidas       |  14.993|\n|Valores perdidos            |       0|\n|Media                       |    0,06|\n|Mediana                     |       0|\n|Moda                        |       0|\n|Mínimo                      |       0|\n|Máximo                      |       8|\n|Primer cuartil (Q1)         |       0|\n|Tercer cuartil (Q3)         |       0|\n|Rango intercuartílico (IQR) |       0|\n|Rango                       |       8|\n|Varianza                    |    0,12|\n|Desviación estándar         |    0,35|\n|Coeficiente de variación    | 609,9 %|\n|Asimetría                   |   9,459|\n|Curtosis                    | 124,425|\n\n\n:::\n:::\n\n\n\n::: {.cell tbl-cap='Detección de valores atípicos — Número de videos (videos)'}\n\n```{.r .cell-code}\ntabla_atipicos(datos$VideoAmt)\n```\n\n::: {.cell-output-display}\n\n\n|Criterio                      | Límite inferior| Límite superior| Atípicos| % del total|\n|:-----------------------------|---------------:|---------------:|--------:|-----------:|\n|Regla de 1,5 × IQR            |               0|               0|      574|       3,8 %|\n|Puntaje z (&#124;z&#124; > 3) |           -0,98|            1,10|      157|       1,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuanti(datos$VideoAmt, \"Videos\", tipo = \"conteo\")\n```\n\n::: {.cell-output-display}\n![Histograma de número de videos](analisis-exploratorio_files/figure-html/graf-VideoAmt-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Diagrama de caja de número de videos](analisis-exploratorio_files/figure-html/graf-VideoAmt-2.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Gráfico de densidad de número de videos](analisis-exploratorio_files/figure-html/graf-VideoAmt-3.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Valores más frecuentes de número de videos](analisis-exploratorio_files/figure-html/graf-VideoAmt-4.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** La variable es **casi constante**: el 96,2 % de los anuncios no incluye video, solo el 3,8 % tiene al menos uno y el máximo es 8. Su media (0,06), mediana y moda son 0, y el coeficiente de variación (609,9 %) es enorme justamente porque la media es casi nula. Los 574 atípicos que marca el IQR (3,8 %) son simplemente los anuncios con video. **Lectura:** con tan poca variabilidad, la variable aporta poca información descriptiva; se recomienda tratarla como dicotómica (tiene o no video) y evaluar en la fase de modelamiento si vale la pena conservarla.\n\n#### `sentiment_score` — Sentimiento del relato (polaridad) {.unnumbered}\n\n\n::: {.cell tbl-cap='Estadísticos descriptivos — Sentimiento del relato (polaridad) (índice de −1 a 1)'}\n\n```{.r .cell-code}\ntabla_estadisticos(datos$sentiment_score)\n```\n\n::: {.cell-output-display}\n\n\n|Estadístico                 |  Valor|\n|:---------------------------|------:|\n|Observaciones válidas       | 14.442|\n|Valores perdidos            |    551|\n|Media                       |   0,28|\n|Mediana                     |   0,30|\n|Moda                        |      0|\n|Mínimo                      |  -0,90|\n|Máximo                      |   0,90|\n|Primer cuartil (Q1)         |   0,10|\n|Tercer cuartil (Q3)         |   0,40|\n|Rango intercuartílico (IQR) |   0,30|\n|Rango                       |   1,80|\n|Varianza                    |   0,08|\n|Desviación estándar         |   0,28|\n|Coeficiente de variación    | 98,5 %|\n|Asimetría                   |  0,232|\n|Curtosis                    |  0,484|\n\n\n:::\n:::\n\n\n\n::: {.cell tbl-cap='Detección de valores atípicos — Sentimiento del relato (polaridad) (índice de −1 a 1)'}\n\n```{.r .cell-code}\ntabla_atipicos(datos$sentiment_score)\n```\n\n::: {.cell-output-display}\n\n\n|Criterio                      | Límite inferior| Límite superior| Atípicos| % del total|\n|:-----------------------------|---------------:|---------------:|--------:|-----------:|\n|Regla de 1,5 × IQR            |           -0,35|            0,85|      786|       5,4 %|\n|Puntaje z (&#124;z&#124; > 3) |           -0,55|            1,11|       74|       0,5 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuanti(datos$sentiment_score, \"Polaridad (−1 a 1)\", tipo = \"continuo\")\n```\n\n::: {.cell-output-display}\n![Histograma de sentimiento del relato (polaridad)](analisis-exploratorio_files/figure-html/graf-sentiment_score-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Diagrama de caja de sentimiento del relato (polaridad)](analisis-exploratorio_files/figure-html/graf-sentiment_score-2.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Gráfico de densidad de sentimiento del relato (polaridad)](analisis-exploratorio_files/figure-html/graf-sentiment_score-3.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![QQ-plot (referencia normal) de sentimiento del relato (polaridad)](analisis-exploratorio_files/figure-html/graf-sentiment_score-4.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** La polaridad del relato es la variable cuantitativa **mejor comportada**: su distribución es prácticamente simétrica (asimetría = 0,23, curtosis = 0,48, prácticamente la de una normal). La media (0,28) y la mediana (0,30) son casi iguales, el 50 % central está entre 0,10 y 0,40 y el rango observado va de -0,90 a 0,90. El 16,1 % de los relatos obtiene una polaridad de exactamente 0 (texto neutro) y los atípicos por IQR (786, 5,4 %) aparecen en los dos extremos. Los 551 valores perdidos corresponden a anuncios para los que no se recuperó la anotación (no son relatos vacíos: en esos casos la mediana de longitud es de 277 caracteres). **Lectura:** en conjunto, los relatos tienden a ser levemente positivos, con poca polaridad extrema.\n\n#### `sentiment_magnitude` — Sentimiento del relato (intensidad) {.unnumbered}\n\n\n::: {.cell tbl-cap='Estadísticos descriptivos — Sentimiento del relato (intensidad) (índice ≥ 0)'}\n\n```{.r .cell-code}\ntabla_estadisticos(datos$sentiment_magnitude)\n```\n\n::: {.cell-output-display}\n\n\n|Estadístico                 |  Valor|\n|:---------------------------|------:|\n|Observaciones válidas       | 14.442|\n|Valores perdidos            |    551|\n|Media                       |   2,13|\n|Mediana                     |   1,60|\n|Moda                        |   0,90|\n|Mínimo                      |      0|\n|Máximo                      |     32|\n|Primer cuartil (Q1)         |   0,80|\n|Tercer cuartil (Q3)         |   2,80|\n|Rango intercuartílico (IQR) |      2|\n|Rango                       |     32|\n|Varianza                    |   4,15|\n|Desviación estándar         |   2,04|\n|Coeficiente de variación    | 95,7 %|\n|Asimetría                   |  2,912|\n|Curtosis                    | 17,202|\n\n\n:::\n:::\n\n\n\n::: {.cell tbl-cap='Detección de valores atípicos — Sentimiento del relato (intensidad) (índice ≥ 0)'}\n\n```{.r .cell-code}\ntabla_atipicos(datos$sentiment_magnitude)\n```\n\n::: {.cell-output-display}\n\n\n|Criterio                      | Límite inferior| Límite superior| Atípicos| % del total|\n|:-----------------------------|---------------:|---------------:|--------:|-----------:|\n|Regla de 1,5 × IQR            |           -2,20|            5,80|      720|       5,0 %|\n|Puntaje z (&#124;z&#124; > 3) |           -3,98|            8,24|      260|       1,8 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuanti(datos$sentiment_magnitude, \"Intensidad del sentimiento\", tipo = \"continuo\")\n```\n\n::: {.cell-output-display}\n![Histograma de sentimiento del relato (intensidad)](analisis-exploratorio_files/figure-html/graf-sentiment_magnitude-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Diagrama de caja de sentimiento del relato (intensidad)](analisis-exploratorio_files/figure-html/graf-sentiment_magnitude-2.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Gráfico de densidad de sentimiento del relato (intensidad)](analisis-exploratorio_files/figure-html/graf-sentiment_magnitude-3.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![QQ-plot (referencia normal) de sentimiento del relato (intensidad)](analisis-exploratorio_files/figure-html/graf-sentiment_magnitude-4.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Mide **cuánta** carga emocional hay en el relato (no su signo) y es una variable acumulativa: crece con la cantidad de texto anotado, por lo que no es directamente comparable entre relatos de distinta extensión. Su distribución es **asimétrica positiva (cola a la derecha)** (asimetría = 2,91), con mediana 1,60 y media 2,13; el 4,1 % de los casos tiene intensidad 0 y el máximo llega a 32 en relatos muy largos. Comparte los 551 valores perdidos de `sentiment_score`. **Lectura:** es una medida de exposición emocional, no de tono; si se usa en el modelamiento conviene normalizarla por la longitud del relato y documentar esa decisión.\n\n#### `total_labels` — Etiquetas de contenido detectadas en las fotos {.unnumbered}\n\n\n::: {.cell tbl-cap='Estadísticos descriptivos — Etiquetas de contenido detectadas en las fotos (etiquetas)'}\n\n```{.r .cell-code}\ntabla_estadisticos(datos$total_labels)\n```\n\n::: {.cell-output-display}\n\n\n|Estadístico                 |    Valor|\n|:---------------------------|--------:|\n|Observaciones válidas       |   14.652|\n|Valores perdidos            |      341|\n|Media                       |    37,28|\n|Mediana                     |       30|\n|Moda                        |       10|\n|Mínimo                      |        1|\n|Máximo                      |      299|\n|Primer cuartil (Q1)         |       18|\n|Tercer cuartil (Q3)         |       48|\n|Rango intercuartílico (IQR) |       30|\n|Rango                       |      298|\n|Varianza                    | 1.063,78|\n|Desviación estándar         |    32,62|\n|Coeficiente de variación    |   87,5 %|\n|Asimetría                   |    2,902|\n|Curtosis                    |   12,948|\n\n\n:::\n:::\n\n\n\n::: {.cell tbl-cap='Detección de valores atípicos — Etiquetas de contenido detectadas en las fotos (etiquetas)'}\n\n```{.r .cell-code}\ntabla_atipicos(datos$total_labels)\n```\n\n::: {.cell-output-display}\n\n\n|Criterio                      | Límite inferior| Límite superior| Atípicos| % del total|\n|:-----------------------------|---------------:|---------------:|--------:|-----------:|\n|Regla de 1,5 × IQR            |             -27|              93|      810|       5,5 %|\n|Puntaje z (&#124;z&#124; > 3) |          -60,57|          135,12|      299|       2,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuanti(datos$total_labels, \"Etiquetas detectadas\", tipo = \"conteo\")\n```\n\n::: {.cell-output-display}\n![Histograma de etiquetas de contenido detectadas en las fotos](analisis-exploratorio_files/figure-html/graf-total_labels-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Diagrama de caja de etiquetas de contenido detectadas en las fotos](analisis-exploratorio_files/figure-html/graf-total_labels-2.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Gráfico de densidad de etiquetas de contenido detectadas en las fotos](analisis-exploratorio_files/figure-html/graf-total_labels-3.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Valores más frecuentes de etiquetas de contenido detectadas en las fotos](analisis-exploratorio_files/figure-html/graf-total_labels-4.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Es un **conteo acumulado** de las etiquetas que la API de visión detectó en el conjunto de fotografías del anuncio (no un promedio por foto), de modo que su magnitud está ligada al número de imágenes de la ficha; interpretarla como «riqueza visual media» exigiría normalizarla. La distribución es **asimétrica positiva (cola a la derecha)** (asimetría = 2,90, curtosis = 12,95), con mínimo 1, mediana 30, media 37,28 y máximo 299 etiquetas. Presenta 341 valores perdidos (anuncios sin fotografía) y 810 atípicos altos por IQR (5,5 %). **Lectura:** variable de conteo con cola derecha marcada; útil como indicador de cuánta información visual contiene la ficha.\n\n#### `total_faces` — Rostros humanos detectados en las fotos {.unnumbered}\n\n\n::: {.cell tbl-cap='Estadísticos descriptivos — Rostros humanos detectados en las fotos (rostros)'}\n\n```{.r .cell-code}\ntabla_estadisticos(datos$total_faces)\n```\n\n::: {.cell-output-display}\n\n\n|Estadístico                 |   Valor|\n|:---------------------------|-------:|\n|Observaciones válidas       |  14.652|\n|Valores perdidos            |     341|\n|Media                       |    0,05|\n|Mediana                     |       0|\n|Moda                        |       0|\n|Mínimo                      |       0|\n|Máximo                      |       6|\n|Primer cuartil (Q1)         |       0|\n|Tercer cuartil (Q3)         |       0|\n|Rango intercuartílico (IQR) |       0|\n|Rango                       |       6|\n|Varianza                    |    0,08|\n|Desviación estándar         |    0,29|\n|Coeficiente de variación    | 599,6 %|\n|Asimetría                   |   8,440|\n|Curtosis                    |  95,032|\n\n\n:::\n:::\n\n\n\n::: {.cell tbl-cap='Detección de valores atípicos — Rostros humanos detectados en las fotos (rostros)'}\n\n```{.r .cell-code}\ntabla_atipicos(datos$total_faces)\n```\n\n::: {.cell-output-display}\n\n\n|Criterio                      | Límite inferior| Límite superior| Atípicos| % del total|\n|:-----------------------------|---------------:|---------------:|--------:|-----------:|\n|Regla de 1,5 × IQR            |               0|               0|      523|       3,6 %|\n|Puntaje z (&#124;z&#124; > 3) |           -0,82|            0,91|      523|       3,6 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuanti(datos$total_faces, \"Rostros detectados\", tipo = \"conteo\")\n```\n\n::: {.cell-output-display}\n![Histograma de rostros humanos detectados en las fotos](analisis-exploratorio_files/figure-html/graf-total_faces-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Diagrama de caja de rostros humanos detectados en las fotos](analisis-exploratorio_files/figure-html/graf-total_faces-2.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Gráfico de densidad de rostros humanos detectados en las fotos](analisis-exploratorio_files/figure-html/graf-total_faces-3.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Valores más frecuentes de rostros humanos detectados en las fotos](analisis-exploratorio_files/figure-html/graf-total_faces-4.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** La variable es **casi constante y casi toda cero**: el 96,4 % de los anuncios no tiene rostros detectados, la media es 0,05 y el máximo 6 (aparecen personas, por ejemplo voluntarios o adoptantes). Como Q1 = Q3 = 0, la regla de 1,5 × IQR marca como atípico todo valor mayor que cero (523 casos, 3,6 %), y el puntaje z detecta exactamente los mismos casos. **Lectura:** es una variable prácticamente dicotómica («¿hay personas en las fotos?»); su utilidad está en esa distinción, no en su valor numérico.\n\n#### `total_colors` — Colores dominantes detectados en las fotos {.unnumbered}\n\n\n::: {.cell tbl-cap='Estadísticos descriptivos — Colores dominantes detectados en las fotos (colores)'}\n\n```{.r .cell-code}\ntabla_estadisticos(datos$total_colors)\n```\n\n::: {.cell-output-display}\n\n\n|Estadístico                 |    Valor|\n|:---------------------------|--------:|\n|Observaciones válidas       |   14.652|\n|Valores perdidos            |      341|\n|Media                       |    39,72|\n|Mediana                     |       30|\n|Moda                        |       10|\n|Mínimo                      |        6|\n|Máximo                      |      300|\n|Primer cuartil (Q1)         |       20|\n|Tercer cuartil (Q3)         |       50|\n|Rango intercuartílico (IQR) |       30|\n|Rango                       |      294|\n|Varianza                    | 1.204,14|\n|Desviación estándar         |    34,70|\n|Coeficiente de variación    |   87,4 %|\n|Asimetría                   |    2,907|\n|Curtosis                    |   12,851|\n\n\n:::\n:::\n\n\n\n::: {.cell tbl-cap='Detección de valores atípicos — Colores dominantes detectados en las fotos (colores)'}\n\n```{.r .cell-code}\ntabla_atipicos(datos$total_colors)\n```\n\n::: {.cell-output-display}\n\n\n|Criterio                      | Límite inferior| Límite superior| Atípicos| % del total|\n|:-----------------------------|---------------:|---------------:|--------:|-----------:|\n|Regla de 1,5 × IQR            |             -25|              95|      920|       6,3 %|\n|Puntaje z (&#124;z&#124; > 3) |          -64,39|          143,82|      286|       2,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuanti(datos$total_colors, \"Colores dominantes\", tipo = \"conteo\")\n```\n\n::: {.cell-output-display}\n![Histograma de colores dominantes detectados en las fotos](analisis-exploratorio_files/figure-html/graf-total_colors-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Diagrama de caja de colores dominantes detectados en las fotos](analisis-exploratorio_files/figure-html/graf-total_colors-2.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Gráfico de densidad de colores dominantes detectados en las fotos](analisis-exploratorio_files/figure-html/graf-total_colors-3.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Valores más frecuentes de colores dominantes detectados en las fotos](analisis-exploratorio_files/figure-html/graf-total_colors-4.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Conteo acumulado de los colores dominantes de todas las fotografías del anuncio; el servicio de visión devuelve hasta diez colores por imagen, de ahí que los valores sean múltiplos de 10 en la mayoría de los casos. El mínimo es 6 (todo anuncio con foto tiene al menos una imagen procesada), la mediana 30, la media 39,72 y el máximo 300; la asimetría es 2,91 y el 6,3 % de los anuncios queda fuera de los límites de 1,5 × IQR. Comparte los 341 valores perdidos de los anuncios sin foto. **Lectura:** igual que `total_labels`, es un indicador del volumen de información visual, sensible al número de fotos.\n\n#### `desc_char_len` — Longitud del relato (caracteres) {.unnumbered}\n\n\n::: {.cell tbl-cap='Estadísticos descriptivos — Longitud del relato (caracteres) (caracteres)'}\n\n```{.r .cell-code}\ntabla_estadisticos(datos$desc_char_len)\n```\n\n::: {.cell-output-display}\n\n\n|Estadístico                 |      Valor|\n|:---------------------------|----------:|\n|Observaciones válidas       |     14.993|\n|Valores perdidos            |          0|\n|Media                       |     339,31|\n|Mediana                     |        238|\n|Moda                        |         12|\n|Mínimo                      |          1|\n|Máximo                      |      6.664|\n|Primer cuartil (Q1)         |        117|\n|Tercer cuartil (Q3)         |        431|\n|Rango intercuartílico (IQR) |        314|\n|Rango                       |      6.663|\n|Varianza                    | 139.402,34|\n|Desviación estándar         |     373,37|\n|Coeficiente de variación    |    110,0 %|\n|Asimetría                   |      4,002|\n|Curtosis                    |     31,426|\n\n\n:::\n:::\n\n\n\n::: {.cell tbl-cap='Detección de valores atípicos — Longitud del relato (caracteres) (caracteres)'}\n\n```{.r .cell-code}\ntabla_atipicos(datos$desc_char_len)\n```\n\n::: {.cell-output-display}\n\n\n|Criterio                      | Límite inferior| Límite superior| Atípicos| % del total|\n|:-----------------------------|---------------:|---------------:|--------:|-----------:|\n|Regla de 1,5 × IQR            |            -354|             902|      883|       5,9 %|\n|Puntaje z (&#124;z&#124; > 3) |         -780,79|        1.459,40|      278|       1,9 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuanti(datos$desc_char_len, \"Caracteres del relato\", tipo = \"continuo\")\n```\n\n::: {.cell-output-display}\n![Histograma de longitud del relato (caracteres)](analisis-exploratorio_files/figure-html/graf-desc_char_len-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Diagrama de caja de longitud del relato (caracteres)](analisis-exploratorio_files/figure-html/graf-desc_char_len-2.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Gráfico de densidad de longitud del relato (caracteres)](analisis-exploratorio_files/figure-html/graf-desc_char_len-3.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![QQ-plot (referencia normal) de longitud del relato (caracteres)](analisis-exploratorio_files/figure-html/graf-desc_char_len-4.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** El relato del rescatista tiene una extensión muy variable: la mediana es de 238 caracteres, el 50 % central va de 117 a 431 y el máximo alcanza 6.664 caracteres. La distribución es **asimétrica positiva (cola a la derecha)** (asimetría = 4,00, curtosis = 31,43): una mayoría de relatos breves y una minoría de textos extensos. La media (339,31 caracteres) supera la mediana, y la regla de 1,5 × IQR marca 883 relatos largos como atípicos (5,9 %). No hay relatos vacíos: el mínimo es de 1 carácter. **Lectura:** la extensión del relato es una de las variables con mayor dispersión relativa (CV = 110,0 %); conviene tratarla en escala logarítmica.\n\n#### `desc_word_count` — Longitud del relato (palabras) {.unnumbered}\n\n\n::: {.cell tbl-cap='Estadísticos descriptivos — Longitud del relato (palabras) (palabras)'}\n\n```{.r .cell-code}\ntabla_estadisticos(datos$desc_word_count)\n```\n\n::: {.cell-output-display}\n\n\n|Estadístico                 |    Valor|\n|:---------------------------|--------:|\n|Observaciones válidas       |   14.993|\n|Valores perdidos            |        0|\n|Media                       |    62,95|\n|Mediana                     |       44|\n|Moda                        |        3|\n|Mínimo                      |        1|\n|Máximo                      |    1.257|\n|Primer cuartil (Q1)         |       21|\n|Tercer cuartil (Q3)         |       81|\n|Rango intercuartílico (IQR) |       60|\n|Rango                       |    1.256|\n|Varianza                    | 4.802,18|\n|Desviación estándar         |    69,30|\n|Coeficiente de variación    |  110,1 %|\n|Asimetría                   |    3,906|\n|Curtosis                    |   30,908|\n\n\n:::\n:::\n\n\n\n::: {.cell tbl-cap='Detección de valores atípicos — Longitud del relato (palabras) (palabras)'}\n\n```{.r .cell-code}\ntabla_atipicos(datos$desc_word_count)\n```\n\n::: {.cell-output-display}\n\n\n|Criterio                      | Límite inferior| Límite superior| Atípicos| % del total|\n|:-----------------------------|---------------:|---------------:|--------:|-----------:|\n|Regla de 1,5 × IQR            |             -69|             171|      862|       5,7 %|\n|Puntaje z (&#124;z&#124; > 3) |         -144,94|          270,85|      272|       1,8 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuanti(datos$desc_word_count, \"Palabras del relato\", tipo = \"continuo\")\n```\n\n::: {.cell-output-display}\n![Histograma de longitud del relato (palabras)](analisis-exploratorio_files/figure-html/graf-desc_word_count-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Diagrama de caja de longitud del relato (palabras)](analisis-exploratorio_files/figure-html/graf-desc_word_count-2.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Gráfico de densidad de longitud del relato (palabras)](analisis-exploratorio_files/figure-html/graf-desc_word_count-3.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![QQ-plot (referencia normal) de longitud del relato (palabras)](analisis-exploratorio_files/figure-html/graf-desc_word_count-4.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Es la misma extensión del relato medida en palabras, así que reproduce el patrón anterior: mediana de 44 palabras, media 62,95, rango de 1 a 1.257 palabras y un 50 % central entre 21 y 81. La asimetría (3,91) y la curtosis (30,91) confirman la cola derecha, con 862 atípicos por IQR (5,7 %). **Lectura:** es una versión equivalente a `desc_char_len` en otra unidad; para el modelamiento basta conservar una de las dos (o estandarizar) para no duplicar la misma información.\n\n### Análisis cualitativo {#cualitativo}\n\nSe analizan las 19 variables cualitativas. Para cada una se reportan: número de categorías (o de valores distintos, si la variable es un identificador), la categoría modal y su peso, las categorías poco frecuentes (definidas como las que reúnen **menos del 1 %** de los anuncios) y la tabla de frecuencias absolutas y relativas, con el gráfico de barras correspondiente. El pastel se incluye solo cuando el número de categorías es pequeño (siete o menos), porque con más categorías deja de ser legible; en las variables de alta cardinalidad la tabla muestra las categorías más frecuentes y el resto agrupado en «Otras».\n\n#### `Type` — Especie {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Especie'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$Type, \"Especie\")\n```\n\n::: {.cell-output-display}\n\n\n|Especie | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:-------|-------------------:|-------------------:|--------------------:|\n|Perro   |               8.132|              54,2 %|               54,2 %|\n|Gato    |               6.861|              45,8 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$Type, \"Especie\", pastel = TRUE, n_top = 10)\n```\n\n::: {.cell-output-display}\n![Distribución por especie](analisis-exploratorio_files/figure-html/graf-cuali-Type-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Composición porcentual por especie](analisis-exploratorio_files/figure-html/graf-cuali-Type-2.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Variable **binaria** y bien balanceada: 54,2 % de los anuncios son de perro y 45,8 % de gato, sin categorías poco frecuentes. Como la diferencia entre categorías es pequeña (8.132 vs. 6.861 anuncios), ninguna categoría domina la tabla y no requiere agrupamiento. **Lectura:** la composición por especie es casi paritaria, lo que permite describir la base sin sesgo evidente hacia perros o gatos.\n\n#### `Gender` — Sexo {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Sexo'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$Gender, \"Sexo\")\n```\n\n::: {.cell-output-display}\n\n\n|Sexo   | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:------|-------------------:|-------------------:|--------------------:|\n|Hembra |               7.277|              48,5 %|               48,5 %|\n|Macho  |               5.536|              36,9 %|               85,5 %|\n|Mixto  |               2.180|              14,5 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$Gender, \"Sexo\", pastel = TRUE, n_top = 10)\n```\n\n::: {.cell-output-display}\n![Distribución por sexo](analisis-exploratorio_files/figure-html/graf-cuali-Gender-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Composición porcentual por sexo](analisis-exploratorio_files/figure-html/graf-cuali-Gender-2.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Tres categorías: la más frecuente es «Hembra» (48,5 %), seguida de «Macho» (36,9 %) y «Mixto» (14,5 %); ninguna es poco frecuente. La categoría «Mixto» no describe el sexo de un animal individual, sino que identifica los anuncios que agrupan **varios animales de distinto sexo** (los mismos casos de `Quantity > 1`). **Lectura:** la variable mezcla un atributo del animal con un atributo del anuncio; al modelar conviene separar ambos significados o analizar el sexo solo en los anuncios de un único animal.\n\n#### `MaturitySize` — Tamaño {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Tamaño'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$MaturitySize, \"Tamaño\")\n```\n\n::: {.cell-output-display}\n\n\n|Tamaño       | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:------------|-------------------:|-------------------:|--------------------:|\n|Mediano      |              10.305|              68,7 %|               68,7 %|\n|Pequeño      |               3.395|              22,6 %|               91,4 %|\n|Grande       |               1.260|               8,4 %|               99,8 %|\n|Extra grande |                  33|               0,2 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$MaturitySize, \"Tamaño\", pastel = TRUE, n_top = 10)\n```\n\n::: {.cell-output-display}\n![Distribución por tamaño](analisis-exploratorio_files/figure-html/graf-cuali-MaturitySize-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Composición porcentual por tamaño](analisis-exploratorio_files/figure-html/graf-cuali-MaturitySize-2.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Escala **ordinal** de cuatro categorías dominada por Mediano (68,7 %); las categorías «Grande» (8,4 %) y sobre todo «Extra grande» (0,2 %, 33 anuncios) son poco frecuentes, y esta última es la única categoría rara de la base. **Lectura:** es una variable casi constante, con una categoría minoritaria muy pequeña; para el modelamiento conviene agrupar «Grande» con «Extra grande» o tratarla como ordinal de tres niveles.\n\n#### `FurLength` — Longitud del pelo {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Longitud del pelo'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$FurLength, \"Longitud del pelo\")\n```\n\n::: {.cell-output-display}\n\n\n|Longitud del pelo | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:-----------------|-------------------:|-------------------:|--------------------:|\n|Corto             |               8.808|              58,7 %|               58,7 %|\n|Mediano           |               5.361|              35,8 %|               94,5 %|\n|Largo             |                 824|               5,5 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$FurLength, \"Longitud del pelo\", pastel = TRUE, n_top = 10)\n```\n\n::: {.cell-output-display}\n![Distribución por longitud del pelo](analisis-exploratorio_files/figure-html/graf-cuali-FurLength-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Composición porcentual por longitud del pelo](analisis-exploratorio_files/figure-html/graf-cuali-FurLength-2.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Escala **ordinal** de tres categorías: Corto (58,7 %),  y 5,5 % de pelo largo; ninguna categoría es poco frecuente. El orden natural (corto \\< mediano \\< largo) permite usar medidas de posición sin perder información. **Lectura:** la mayoría de las fichas describe animales de pelo corto o mediano; el pelo largo es minoritario, pero con suficiente frecuencia para conservar la categoría.\n\n#### `Vaccinated` — Vacunado {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Vacunado'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$Vaccinated, \"Vacunado\")\n```\n\n::: {.cell-output-display}\n\n\n|Vacunado       | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:--------------|-------------------:|-------------------:|--------------------:|\n|No             |               7.227|              48,2 %|               48,2 %|\n|Sí             |               5.898|              39,3 %|               87,5 %|\n|No está seguro |               1.868|              12,5 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$Vaccinated, \"Vacunado\", pastel = TRUE, n_top = 10)\n```\n\n::: {.cell-output-display}\n![Distribución por vacunado](analisis-exploratorio_files/figure-html/graf-cuali-Vaccinated-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Composición porcentual por vacunado](analisis-exploratorio_files/figure-html/graf-cuali-Vaccinated-2.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Tres categorías nominales: No (48,2 %), seguida de «Sí» (39,3 %) y «No está seguro» (12,5 %); sin categorías raras. La categoría intermedia es informativa por sí misma: refleja fichas en las que el rescatista no tiene certeza del estado sanitario. **Lectura:** más de la mitad de los anuncios no declara vacunación o no está seguro de ella.\n\n#### `Dewormed` — Desparasitado {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Desparasitado'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$Dewormed, \"Desparasitado\")\n```\n\n::: {.cell-output-display}\n\n\n|Desparasitado  | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:--------------|-------------------:|-------------------:|--------------------:|\n|Sí             |               8.397|              56,0 %|               56,0 %|\n|No             |               4.815|              32,1 %|               88,1 %|\n|No está seguro |               1.781|              11,9 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$Dewormed, \"Desparasitado\", pastel = TRUE, n_top = 10)\n```\n\n::: {.cell-output-display}\n![Distribución por desparasitado](analisis-exploratorio_files/figure-html/graf-cuali-Dewormed-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Composición porcentual por desparasitado](analisis-exploratorio_files/figure-html/graf-cuali-Dewormed-2.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Tres categorías; la moda es «Sí» (56,0 %), seguida de «No» (32,1 %) y «No está seguro» (11,9 %). Es la única de las tres variables sanitarias en la que la respuesta afirmativa es mayoritaria. **Lectura:** la desparasitación se declara con más frecuencia que la vacunación y la esterilización, lo que sugiere que es el cuidado más común en los animales publicados.\n\n#### `Sterilized` — Esterilizado {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Esterilizado'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$Sterilized, \"Esterilizado\")\n```\n\n::: {.cell-output-display}\n\n\n|Esterilizado   | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:--------------|-------------------:|-------------------:|--------------------:|\n|No             |              10.077|              67,2 %|               67,2 %|\n|Sí             |               3.101|              20,7 %|               87,9 %|\n|No está seguro |               1.815|              12,1 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$Sterilized, \"Esterilizado\", pastel = TRUE, n_top = 10)\n```\n\n::: {.cell-output-display}\n![Distribución por esterilizado](analisis-exploratorio_files/figure-html/graf-cuali-Sterilized-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Composición porcentual por esterilizado](analisis-exploratorio_files/figure-html/graf-cuali-Sterilized-2.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Tres categorías con moda en «No» (67,2 %); solo 20,7 % de los anuncios declara esterilización y 12,1 % no está seguro. **Lectura:** casi cuatro de cada cinco anuncios corresponden a animales no esterilizados o de estado desconocido; junto con la vacunación, es la información sanitaria que más falta en las fichas.\n\n#### `Health` — Estado de salud {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Estado de salud'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$Health, \"Estado de salud\")\n```\n\n::: {.cell-output-display}\n\n\n|Estado de salud | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:---------------|-------------------:|-------------------:|--------------------:|\n|Sano            |              14.478|              96,6 %|               96,6 %|\n|Lesión leve     |                 481|               3,2 %|               99,8 %|\n|Lesión grave    |                  34|               0,2 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$Health, \"Estado de salud\", pastel = TRUE, n_top = 10)\n```\n\n::: {.cell-output-display}\n![Distribución por estado de salud](analisis-exploratorio_files/figure-html/graf-cuali-Health-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Composición porcentual por estado de salud](analisis-exploratorio_files/figure-html/graf-cuali-Health-2.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Escala **ordinal** de tres niveles **casi constante**: Sano concentra el 96,6 % de los anuncios, mientras «Lesión leve» aparece en el 3,2 % y «Lesión grave» en el 0,2 % (apenas 34 casos, categoría poco frecuente). **Lectura:** la variable aporta muy poca variabilidad; en la práctica equivale a una dicotomía «sano / no sano», y así conviene tratarla en el modelamiento.\n\n#### `AdoptionSpeed` — Velocidad de adopción (variable respuesta) {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Velocidad de adopción (variable respuesta)'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$AdoptionSpeed, \"Velocidad de adopción\")\n```\n\n::: {.cell-output-display}\n\n\n|Velocidad de adopción | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:---------------------|-------------------:|-------------------:|--------------------:|\n|Sin adopción          |               4.197|              28,0 %|               28,0 %|\n|8–30 días             |               4.037|              26,9 %|               54,9 %|\n|31–90 días            |               3.259|              21,7 %|               76,7 %|\n|1–7 días              |               3.090|              20,6 %|               97,3 %|\n|Mismo día             |                 410|               2,7 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$AdoptionSpeed, \"Velocidad de adopción\", pastel = TRUE, n_top = 10)\n```\n\n::: {.cell-output-display}\n![Distribución por velocidad de adopción](analisis-exploratorio_files/figure-html/graf-cuali-AdoptionSpeed-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Composición porcentual por velocidad de adopción](analisis-exploratorio_files/figure-html/graf-cuali-AdoptionSpeed-2.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Variable **ordinal** de cinco categorías y **respuesta** del estudio. La categoría más frecuente es «Sin adopción» (28,0 %), seguida de «8–30 días» (26,9 %), «31–90 días» (21,7 %) y «1–7 días» (20,6 %); la adopción el mismo día es la categoría poco frecuente, con 410 anuncios (2,7 %). El perfil es de **desbalance moderado**: las cuatro categorías principales pesan entre el 20 % y el 28 %, pero «Mismo día» queda muy por debajo. **Lectura:** el orden natural de las categorías permite tratarla como respuesta ordinal; el desbalance de la clase minoritaria exige pesos o remuestreo en la fase de modelamiento.\n\n#### `Color1` — Color principal {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Color principal'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$Color1, \"Código de color principal\")\n```\n\n::: {.cell-output-display}\n\n\n|Código de color principal | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:-------------------------|-------------------:|-------------------:|--------------------:|\n|1                         |               7.427|              49,5 %|               49,5 %|\n|2                         |               3.750|              25,0 %|               74,5 %|\n|3                         |                 947|               6,3 %|               80,9 %|\n|5                         |                 884|               5,9 %|               86,8 %|\n|6                         |                 684|               4,6 %|               91,3 %|\n|7                         |                 667|               4,4 %|               95,8 %|\n|4                         |                 634|               4,2 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$Color1, \"Código de color principal\", pastel = TRUE, n_top = 10)\n```\n\n::: {.cell-output-display}\n![Distribución por código de color principal](analisis-exploratorio_files/figure-html/graf-cuali-Color1-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Composición porcentual por código de color principal](analisis-exploratorio_files/figure-html/graf-cuali-Color1-2.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Siete códigos de color (el diccionario de nombres no forma parte de la base de trabajo, por lo que se conservan como identificadores). La distribución es muy concentrada: el código 1 reúne el 49,5 % de los anuncios y el código 2 otro 25,0 %; entre los dos suman 74,5 %. Ninguna categoría es poco frecuente y solo tres códigos superan el 6 %. **Lectura:** la ficha describe un color principal en todos los anuncios, pero la diversidad real es baja: casi tres de cada cuatro animales se anuncian con uno de dos colores.\n\n#### `Color2` — Segundo color {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Segundo color'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$Color2, \"Código de segundo color\")\n```\n\n::: {.cell-output-display}\n\n\n|Código de segundo color | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:-----------------------|-------------------:|-------------------:|--------------------:|\n|0                       |               4.471|              29,8 %|               29,8 %|\n|7                       |               3.438|              22,9 %|               52,8 %|\n|2                       |               3.313|              22,1 %|               74,8 %|\n|5                       |               1.128|               7,5 %|               82,4 %|\n|6                       |               1.063|               7,1 %|               89,5 %|\n|4                       |                 870|               5,8 %|               95,3 %|\n|3                       |                 710|               4,7 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$Color2, \"Código de segundo color\", pastel = TRUE, n_top = 10)\n```\n\n::: {.cell-output-display}\n![Distribución por código de segundo color](analisis-exploratorio_files/figure-html/graf-cuali-Color2-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Composición porcentual por código de segundo color](analisis-exploratorio_files/figure-html/graf-cuali-Color2-2.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Siete valores, donde el código 0 significa «sin segundo color» y aparece en el 29,8 % de los anuncios; entre los colores declarados, los códigos 7 (22,9 %) y 2 (22,1 %) son los más frecuentes. **Lectura:** casi un tercio de las fichas describe un solo color, lo que convierte al 0 en una categoría informativa (fichas menos detalladas) y no en un dato perdido.\n\n#### `Color3` — Tercer color {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Tercer color'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$Color3, \"Código de tercer color\")\n```\n\n::: {.cell-output-display}\n\n\n|Código de tercer color | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:----------------------|-------------------:|-------------------:|--------------------:|\n|0                      |              10.604|              70,7 %|               70,7 %|\n|7                      |               3.221|              21,5 %|               92,2 %|\n|5                      |                 417|               2,8 %|               95,0 %|\n|6                      |                 378|               2,5 %|               97,5 %|\n|4                      |                 198|               1,3 %|               98,8 %|\n|3                      |                 175|               1,2 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$Color3, \"Código de tercer color\", pastel = TRUE, n_top = 10)\n```\n\n::: {.cell-output-display}\n![Distribución por código de tercer color](analisis-exploratorio_files/figure-html/graf-cuali-Color3-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![Composición porcentual por código de tercer color](analisis-exploratorio_files/figure-html/graf-cuali-Color3-2.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Seis valores; el código 0 («sin tercer color») domina con el 70,7 % de los anuncios y el resto se reparte entre códigos minoritarios, de los cuales el 7 (21,5 %) es el más común. **Lectura:** la descripción de colores pierde detalle a medida que se avanza en la ficha — Color1 está diligenciado en el 100 % de los anuncios, Color2 en el 70,2 % y Color3 solo en el 29,3 % —, lo que es coherente con un esfuerzo decreciente al llenar el formulario.\n\n#### `Breed1` — Raza principal {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Raza principal'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$Breed1, \"Código de raza principal\", n_top = 11)\n```\n\n::: {.cell-output-display}\n\n\n|Código de raza principal | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:------------------------|-------------------:|-------------------:|--------------------:|\n|307                      |               5.927|              39,5 %|               39,5 %|\n|266                      |               3.634|              24,2 %|               63,8 %|\n|265                      |               1.258|               8,4 %|               72,2 %|\n|299                      |                 342|               2,3 %|               74,4 %|\n|264                      |                 296|               2,0 %|               76,4 %|\n|292                      |                 264|               1,8 %|               78,2 %|\n|285                      |                 221|               1,5 %|               79,7 %|\n|141                      |                 205|               1,4 %|               81,0 %|\n|205                      |                 190|               1,3 %|               82,3 %|\n|179                      |                 167|               1,1 %|               83,4 %|\n|Otras (166 categorías)   |               2.489|              16,6 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"1\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$Breed1, \"Código de raza principal\", pastel = FALSE, n_top = 11)\n```\n\n::: {.cell-output-display}\n![Categorías más frecuentes de código de raza principal](analisis-exploratorio_files/figure-html/graf-cuali-Breed1-1.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Variable de **alta cardinalidad**: 176 códigos distintos de raza. El más frecuente (307) concentra el 39,5 % de los anuncios, los diez primeros reúnen el 83,4 % y hay 164 códigos con menos del 1 % de los casos, que juntos representan el 14,5 % de los anuncios. **Lectura:** una tabla de frecuencia completa sería inmanejable y la mitad de las categorías sería ruido; para el modelamiento conviene agrupar las razas raras en una categoría «otras» (o usar una codificación que agrupe por frecuencia) y conservar el código tal como lo publica la plataforma, ya que el diccionario de nombres no está disponible en la base de trabajo.\n\n#### `Breed2` — Segunda raza {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Segunda raza'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$Breed2, \"Código de segunda raza\", n_top = 11)\n```\n\n::: {.cell-output-display}\n\n\n|Código de segunda raza | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:----------------------|-------------------:|-------------------:|--------------------:|\n|0                      |              10.762|              71,8 %|               71,8 %|\n|307                    |               1.727|              11,5 %|               83,3 %|\n|266                    |                 599|               4,0 %|               87,3 %|\n|265                    |                 321|               2,1 %|               89,4 %|\n|299                    |                 138|               0,9 %|               90,4 %|\n|264                    |                 125|               0,8 %|               91,2 %|\n|292                    |                 105|               0,7 %|               91,9 %|\n|218                    |                  91|               0,6 %|               92,5 %|\n|141                    |                  86|               0,6 %|               93,1 %|\n|285                    |                  78|               0,5 %|               93,6 %|\n|Otras (125 categorías) |                 961|               6,4 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"1\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$Breed2, \"Código de segunda raza\", pastel = FALSE, n_top = 11)\n```\n\n::: {.cell-output-display}\n![Categorías más frecuentes de código de segunda raza](analisis-exploratorio_files/figure-html/graf-cuali-Breed2-1.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** 135 códigos distintos, pero con un valor dominante: el código 0 («sin segunda raza») aparece en el 71,8 % de los anuncios. Entre los que sí declaran una segunda raza, los tres códigos más frecuentes son 307, 266, 265, y hay 131 códigos con menos del 1 % de los casos. **Lectura:** la mayoría de las fichas declara una sola raza; la segunda raza es una variable escasa y muy fragmentada, por lo que su aporte descriptivo es limitado.\n\n#### `State` — Estado o territorio (ubicación) {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Estado o territorio (ubicación)'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$State, \"Código de estado\", n_top = 11)\n```\n\n::: {.cell-output-display}\n\n\n|Código de estado     | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:--------------------|-------------------:|-------------------:|--------------------:|\n|41326                |               8.714|              58,1 %|               58,1 %|\n|41401                |               3.845|              25,6 %|               83,8 %|\n|41327                |                 843|               5,6 %|               89,4 %|\n|41336                |                 507|               3,4 %|               92,8 %|\n|41330                |                 420|               2,8 %|               95,6 %|\n|41332                |                 253|               1,7 %|               97,3 %|\n|41324                |                 137|               0,9 %|               98,2 %|\n|41325                |                 110|               0,7 %|               98,9 %|\n|41335                |                  85|               0,6 %|               99,5 %|\n|41361                |                  26|               0,2 %|               99,6 %|\n|Otras (4 categorías) |                  53|               0,4 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"1\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$State, \"Código de estado\", pastel = FALSE, n_top = 11)\n```\n\n::: {.cell-output-display}\n![Categorías más frecuentes de código de estado](analisis-exploratorio_files/figure-html/graf-cuali-State-1.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** 14 códigos de ubicación con una concentración geográfica marcada: el código 41326 agrupa el 58,1 % de los anuncios y los otros dos códigos principales suman 31,3 %, de modo que los tres primeros explican el 89,4 %. Hay 8 códigos con menos del 1 % de los anuncios (2,7 % del total). **Lectura:** la base está fuertemente concentrada en tres territorios; los códigos minoritarios son candidatos a agruparse y, al no contar con el diccionario de nombres, conviene conservarlos como identificadores.\n\n#### `Name` — Nombre del animal {.unnumbered}\n\n\n::: {.cell tbl-cap='Distribución de frecuencias — Nombre del animal'}\n\n```{.r .cell-code}\ntabla_frecuencias(datos$Name, \"Nombre\", n_top = 11)\n```\n\n::: {.cell-output-display}\n\n\n|Nombre                  | Frecuencia absoluta| Frecuencia relativa| Frecuencia acumulada|\n|:-----------------------|-------------------:|-------------------:|--------------------:|\n|Baby                    |                  66|               0,5 %|                0,5 %|\n|Lucky                   |                  64|               0,5 %|                0,9 %|\n|Brownie                 |                  54|               0,4 %|                1,3 %|\n|No Name                 |                  54|               0,4 %|                1,7 %|\n|Mimi                    |                  52|               0,4 %|                2,1 %|\n|Blackie                 |                  49|               0,4 %|                2,5 %|\n|Puppy                   |                  45|               0,3 %|                2,8 %|\n|Kittens                 |                  39|               0,3 %|                3,1 %|\n|Kitty                   |                  39|               0,3 %|                3,4 %|\n|Max                     |                  39|               0,3 %|                3,6 %|\n|Otras (9050 categorías) |              13.235|              96,4 %|              100,0 %|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"1\"}\n\n```{.r .cell-code}\ngraficos_cuali(datos$Name, \"Nombre\", pastel = FALSE, n_top = 11)\n```\n\n::: {.cell-output-display}\n![Categorías más frecuentes de nombre](analisis-exploratorio_files/figure-html/graf-cuali-Name-1.png){width=100%}\n:::\n:::\n\n\n**Interpretación.** Variable nominal de **alta cardinalidad**: 9.060 nombres distintos sobre 14.993 anuncios (proporción de valores distintos 60,4 %), 1.257 anuncios sin nombre y una moda (Baby) que apenas reúne el 0,4 % de los casos. Los diez nombres más repetidos (Baby, Lucky, Brownie…) suman menos del 3,6 % de los anuncios con nombre. **Lectura:** como categoría no aporta información agregada; sí aporta la distinción binaria «tiene nombre / no tiene nombre», que puede usarse como indicador del cuidado puesto en la ficha.\n\n#### `Description` — Relato del rescatista {.unnumbered}\n\n\n::: {.cell tbl-cap='Cardinalidad — Relato del rescatista'}\n\n```{.r .cell-code}\ntabla_cardinalidad(datos$Description)\n```\n\n::: {.cell-output-display}\n\n\n|Verificación                    |    Resultado|\n|:-------------------------------|------------:|\n|Observaciones                   |       14.993|\n|Valores perdidos                |            0|\n|Categorías distintas            |       14.032|\n|Proporción de valores distintos |       93,6 %|\n|Categoría más frecuente         | For Adoption|\n|Frecuencia de la moda           |        1,1 %|\n\n\n:::\n:::\n\n\n**Interpretación.** Texto libre con 14.032 valores distintos (93,6 % de unicidad) y una moda (For Adoption) que corresponde a una plantilla y solo representa el 1,1 % de los anuncios. Una tabla de frecuencias por categorías no tiene sentido aquí, y tampoco un gráfico de barras: el texto se aprovecha a través de sus dos derivadas cuantitativas, la longitud (`desc_char_len`, `desc_word_count`) y el sentimiento (`sentiment_score`, `sentiment_magnitude`), analizadas en la parte cuantitativa. **Lectura:** el relato es la fuente de información más rica de la ficha, pero su explotación exige tratarlo como texto, no como categoría.\n\n#### `PetID` — Identificador del anuncio {.unnumbered}\n\n\n::: {.cell tbl-cap='Cardinalidad — Identificador del anuncio'}\n\n```{.r .cell-code}\ntabla_cardinalidad(datos$PetID)\n```\n\n::: {.cell-output-display}\n\n\n|Verificación                    | Resultado|\n|:-------------------------------|---------:|\n|Observaciones                   |    14.993|\n|Valores perdidos                |         0|\n|Categorías distintas            |    14.993|\n|Proporción de valores distintos |   100,0 %|\n|Categoría más frecuente         | 0008c5398|\n|Frecuencia de la moda           |     0,0 %|\n\n\n:::\n:::\n\n\n**Interpretación.** 14.993 valores distintos para 14.993 filas: proporción de valores distintos del 100,0 % y frecuencia de la moda de 0,0 %. La verificación de duplicados confirma 0 identificadores repetidos. **Lectura:** no es una variable de análisis, es la **clave** que une los anuncios con las anotaciones de texto e imagen; se documenta aquí para dejar constancia de que identifica unidades únicas.\n\n#### `RescuerID` — Identificador del rescatista {.unnumbered}\n\n\n::: {.cell tbl-cap='Cardinalidad — Identificador del rescatista'}\n\n```{.r .cell-code}\ntabla_cardinalidad(datos$RescuerID)\n```\n\n::: {.cell-output-display}\n\n\n|Verificación                    |                        Resultado|\n|:-------------------------------|--------------------------------:|\n|Observaciones                   |                           14.993|\n|Valores perdidos                |                                0|\n|Categorías distintas            |                            5.595|\n|Proporción de valores distintos |                           37,3 %|\n|Categoría más frecuente         | fa90fa5b1ee11c86938398b60abc32cb|\n|Frecuencia de la moda           |                            3,1 %|\n\n\n:::\n:::\n\n\n**Interpretación.** 5.595 rescatistas distintos; el más activo publica el 3,1 % de los anuncios y los diez más activos, el 12,7 %. Hay 5.590 rescatistas con menos del 1 % de los anuncios, que en conjunto representan el 90,7 % de la base. **Lectura:** los anuncios **no son independientes** entre sí: un mismo rescatista publica varios animales, con prácticas y textos similares; por eso esta variable debe usarse para **agrupar** las particiones de entrenamiento y prueba (y nunca como predictor), para evitar fuga de información.\n\n### Nota de alcance y supuestos {#alcance}\n\n**Alcance.** Los 31 análisis anteriores son estrictamente univariados: cada variable se describió por separado, con sus propias medidas y gráficos. No se incluyeron cruces de variables, medidas de asociación ni correlaciones, y tampoco técnicas multivariadas (componentes principales, agrupamiento) ni modelos de clasificación: todo eso corresponde a las entregas siguientes.\n\n**Supuestos y decisiones documentadas.**\n\n1.  **Valores perdidos sin imputar.** Las cinco variables con faltantes pertenecen al enriquecimiento (nombre, sentimiento y anotaciones de imagen). Se reportan y se describen solo con los casos válidos; la estrategia de imputación se definirá en la fase de modelamiento.\n2.  **Los faltantes no son aleatorios.** El sentimiento falta en anuncios para los que no se recuperó la anotación de la API (no en relatos vacíos) y las variables de imagen faltan en los anuncios sin fotografía; conviene tratarlos con indicadores de ausencia.\n3.  **Conteos acumulados.** `total_labels`, `total_faces` y `total_colors` acumulan las anotaciones de todas las fotografías del anuncio, no son promedios por imagen; su magnitud depende del número de fotos de la ficha.\n4.  **Códigos sin diccionario.** Las razas, los colores y los estados se conservan como identificadores numéricos porque los archivos `breed_labels.csv`, `color_labels.csv` y `state_labels.csv` de la competencia no forman parte de la carpeta `data/` del proyecto. Si se agregan, las tablas se pueden etiquetar sin cambiar el análisis.\n5.  **Atípicos conservados.** No se eliminó ningún registro: los valores atípicos se documentaron con dos criterios y se interpretaron, porque en esta base corresponden a casos reales (animales mayores, anuncios de refugios, fichas muy detalladas).\n6.  **Forma de las distribuciones.** La asimetría y la curtosis se calcularon con los estimadores muestrales tipo 2 de `e1071` (la curtosis es *exceso* respecto de la normal).\n7.  **Reproducibilidad.** Todo el análisis se ejecuta al construir el sitio con `quarto render`, a partir de `data/petfinder_enriquecido_final.csv` y del script [`scripts/01_dataset_enriquecido.R`](../scripts/01_dataset_enriquecido.R).\n\nCon este panorama univariado quedan identificadas las variables que requieren decisiones de tratamiento antes de modelar: las casi constantes (`Health`, `total_faces`, `VideoAmt`), las de dos regímenes (`Fee`, `Quantity`) y las de alta cardinalidad (`Breed1`, `State`).\n",
    "supporting": [
      "analisis-exploratorio_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}