{
  "hash": "ebb71639bbe39425ddad596bbd66c792",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Descripción del Conjunto de Datos\"\nsubtitle: \"Composición del conjunto de datos PetFinder.\"\nauthor: \"Jared Mijail Ramírez Escalante · María Paula Silva Capera\"\n---\n\n::: action-bar\n<button class=\"btn-print\" onclick=\"window.print()\">PDF</button>\n:::\n\n\nA continuación se describe el contenido del conjunto datos PetFinder según el número de unidades de observación\n(anuncios), el número de variables y su tipificación y los valores faltantes a nivel general y particular.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nest <- c(\n  \"Unidades de observación\"   = paste(ent(nrow(datos)), \"anuncios\"),\n  \"Variables cualitativas\"    = sprintf(\"%d (%.1f %%)\", length(VARS_CAT),\n                                        100 * length(VARS_CAT) / ncol(datos)),\n  \"Variables cuantitativas\"   = sprintf(\"%d (%.1f %%)\", length(VARS_NUM),\n                                        100 * length(VARS_NUM) / ncol(datos)),\n  \"Valores faltantes\"         = sprintf(\"%s (%.2f %%)\", ent(sum(is.na(datos))),\n                                        100 * mean(is.na(datos))),\n  \"Filas duplicadas\"          = ent(sum(duplicated(datos))),\n  \"Identificadores duplicados\" = ent(sum(duplicated(datos$PetID)))\n)\n\nceldas <- sprintf(\"**%s**: %s\", names(est), est)\ngrilla <- matrix(celdas, nrow = 2, byrow = TRUE)\n\nknitr::kable(grilla, col.names = rep(\"\", 3), align = \"ccc\")\n```\n\n::: {.cell-output-display}\n\n\n|                                              |                                         |                                          |\n|:--------------------------------------------:|:---------------------------------------:|:----------------------------------------:|\n| **Unidades de observación**: 14.993 anuncios | **Variables cualitativas**: 19 (61.3 %) | **Variables cuantitativas**: 12 (38.7 %) |\n|    **Valores faltantes**: 3.382 (0.73 %)     |         **Filas duplicadas**: 0         |    **Identificadores duplicados**: 0     |\n\n\n:::\n:::\n\n\n### Tipos de Variables\nLas 31 variables se clasifican por su naturaleza y su escala de medición. \nLa columna *Fuente* distingue las variables originales de las que se construyeron \nen el [enriquecimiento](dataset.qmd) (texto e imagen).\n\n\n::: {.cell tbl-cap='Clasificación de las variables cualitativas por tipo, escala y origen'}\n\n```{.r .cell-code}\nclasificacion_cuali <- tibble::tribble(\n  ~Variable, ~`Tipo`, ~Escala, ~Fuente,\n  \"PetID\",              \"Caracter\",  \"Nominal\",   \"Original\",\n  \"Name\",               \"Caracter\",  \"Nominal\",   \"Original\",\n  \"Type\",               \"Factor\",    \"Nominal\",   \"Original\",\n  \"Breed1\",             \"Factor\",    \"Nominal\",   \"Original\",\n  \"Breed2\",             \"Factor\",    \"Nominal\",   \"Original\",\n  \"Gender\",             \"Factor\",    \"Nominal\",   \"Original\",\n  \"Color1\",             \"Factor\",    \"Nominal\",   \"Original\",\n  \"Color2\",             \"Factor\",    \"Nominal\",   \"Original\",\n  \"Color3\",             \"Factor\",    \"Nominal\",   \"Original\",\n  \"Vaccinated\",         \"Factor\",    \"Nominal\",   \"Original\",\n  \"Dewormed\",           \"Factor\",    \"Nominal\",   \"Original\",\n  \"Sterilized\",         \"Factor\",    \"Nominal\",   \"Original\",\n  \"State\",              \"Factor\",    \"Nominal\",   \"Original\",\n  \"RescuerID\",          \"Caracter\",  \"Nominal\",   \"Original\",\n  \"Description\",        \"Texto\",     \"Nominal\",   \"Original\",\n  \"MaturitySize\",       \"Factor\",    \"Ordinal\",   \"Original\",\n  \"FurLength\",          \"Factor\",    \"Ordinal\",   \"Original\",\n  \"Health\",             \"Factor\",    \"Ordinal\",   \"Original\",\n  \"AdoptionSpeed\",      \"Factor\",    \"Ordinal\",   \"Original\"\n) |>\n  dplyr::arrange(Escala)\n\nclasificacion_cuali |> knitr::kable(align = c(\"l\", \"l\", \"l\", \"l\", \"l\"))\n```\n\n::: {.cell-output-display}\n\n\n|Variable      |Tipo     |Escala  |Fuente   |\n|:-------------|:--------|:-------|:--------|\n|PetID         |Caracter |Nominal |Original |\n|Name          |Caracter |Nominal |Original |\n|Type          |Factor   |Nominal |Original |\n|Breed1        |Factor   |Nominal |Original |\n|Breed2        |Factor   |Nominal |Original |\n|Gender        |Factor   |Nominal |Original |\n|Color1        |Factor   |Nominal |Original |\n|Color2        |Factor   |Nominal |Original |\n|Color3        |Factor   |Nominal |Original |\n|Vaccinated    |Factor   |Nominal |Original |\n|Dewormed      |Factor   |Nominal |Original |\n|Sterilized    |Factor   |Nominal |Original |\n|State         |Factor   |Nominal |Original |\n|RescuerID     |Caracter |Nominal |Original |\n|Description   |Texto    |Nominal |Original |\n|MaturitySize  |Factor   |Ordinal |Original |\n|FurLength     |Factor   |Ordinal |Original |\n|Health        |Factor   |Ordinal |Original |\n|AdoptionSpeed |Factor   |Ordinal |Original |\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nclasificacion_cuali |> count(Escala) |>\n  ggplot(aes(x = n, y = fct_reorder(Escala, n))) +\n  geom_col(fill = \"#2e7d9a\", width = 0.68) +\n  geom_text(aes(label = n), hjust = -0.4, colour = \"#1f2937\", size = 3.4) +\n  scale_x_continuous(expand = expansion(mult = c(0, 0.15))) +\n  labs(title = \"Variables cualitativas por escala\", x = \"Número de variables\", y = NULL) + tema_u()\n```\n\n::: {.cell-output-display}\n![Número de variables cualitativas por escala](descripcion_files/figure-html/general-tipos-1.png){width=100%}\n:::\n\n```{.r .cell-code}\nclasificacion_cuali |> count(Tipo) |>\n  ggplot(aes(x = \"\", y = n, fill = Tipo)) +\n  geom_col(width = 1, colour = \"white\") + coord_polar(\"y\") +\n  labs(title = \"Composición por escala (cualitativas)\", x = NULL, y = NULL) +\n  theme_minimal(base_size = 11.5) +\n  theme(plot.background = element_rect(fill = \"white\", colour = NA),\n        plot.title = element_text(colour = \"#1a3a5c\", face = \"bold\", size = 11.5),\n        legend.title = element_blank(), legend.text = element_text(size = 9),\n        axis.text = element_blank(), panel.grid = element_blank())\n```\n\n::: {.cell-output-display}\n![Composición porcentual de las variables cualitativas por escala](descripcion_files/figure-html/general-tipos-2.png){width=100%}\n:::\n:::\n\nDe las 19 variables cualitativas se tiene que 15 de ellas son nominales frente a las 4 restantes que son ordinales. Se cuenta con variables de tipo caracter, factor y texto donde la categoría predominante es factor. Todas las variables hacen parte del conjunto de datos original.\n\n\n\n\n::: {.cell tbl-cap='Clasificación de las variables cuantitativas por tipo, escala y origen'}\n\n```{.r .cell-code}\nclasificacion_cuanti <- tibble::tribble(\n  ~Variable, ~`Tipo`, ~Escala, ~Fuente,\n  \"Age\",                \"Entero\",    \"Razón\",  \"Original\",\n  \"Quantity\",           \"Entero\",    \"Razón\",  \"Original\",\n  \"Fee\",                \"Entero\",    \"Razón\",  \"Original\",\n  \"VideoAmt\",           \"Entero\",    \"Razón\",  \"Original\",\n  \"PhotoAmt\",           \"Entero\",    \"Razón\",  \"Original\",\n  \"sentiment_score\",    \"Numérico\",  \"Intervalo\", \"Enriquecimiento (texto)\",\n  \"sentiment_magnitude\",\"Numérico\",  \"Razón\",  \"Enriquecimiento (texto)\",\n  \"total_labels\",       \"Entero\",    \"Razón\",  \"Enriquecimiento (imagen)\",\n  \"total_faces\",        \"Entero\",    \"Razón\",  \"Enriquecimiento (imagen)\",\n  \"total_colors\",       \"Entero\",    \"Razón\",  \"Enriquecimiento (imagen)\",\n  \"desc_char_len\",      \"Entero\",    \"Razón\",  \"Derivada del texto\",\n  \"desc_word_count\",    \"Entero\",    \"Razón\",  \"Derivada del texto\"\n) |>\n  dplyr::arrange(Escala)\n\nclasificacion_cuanti |> knitr::kable(align = c(\"l\", \"l\", \"l\", \"l\", \"l\"))\n```\n\n::: {.cell-output-display}\n\n\n|Variable            |Tipo     |Escala    |Fuente                   |\n|:-------------------|:--------|:---------|:------------------------|\n|sentiment_score     |Numérico |Intervalo |Enriquecimiento (texto)  |\n|Age                 |Entero   |Razón     |Original                 |\n|Quantity            |Entero   |Razón     |Original                 |\n|Fee                 |Entero   |Razón     |Original                 |\n|VideoAmt            |Entero   |Razón     |Original                 |\n|PhotoAmt            |Entero   |Razón     |Original                 |\n|sentiment_magnitude |Numérico |Razón     |Enriquecimiento (texto)  |\n|total_labels        |Entero   |Razón     |Enriquecimiento (imagen) |\n|total_faces         |Entero   |Razón     |Enriquecimiento (imagen) |\n|total_colors        |Entero   |Razón     |Enriquecimiento (imagen) |\n|desc_char_len       |Entero   |Razón     |Derivada del texto       |\n|desc_word_count     |Entero   |Razón     |Derivada del texto       |\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nclasificacion_cuanti |> count(Escala) |>\n  ggplot(aes(x = n, y = fct_reorder(Escala, n))) +\n  geom_col(fill = \"#2e7d9a\", width = 0.68) +\n  geom_text(aes(label = n), hjust = -0.4, colour = \"#1f2937\", size = 3.4) +\n  scale_x_continuous(expand = expansion(mult = c(0, 0.15))) +\n  labs(title = \"Variables cuantitativas por escala\", x = \"Número de variables\", y = NULL) + tema_u()\n```\n\n::: {.cell-output-display}\n![Número de variables cuantitativas por escala](descripcion_files/figure-html/general-tipos-cuanti-1.png){width=100%}\n:::\n\n```{.r .cell-code}\nclasificacion_cuanti |> count(Tipo) |>\n  ggplot(aes(x = \"\", y = n, fill = Tipo)) +\n  geom_col(width = 1, colour = \"white\") + coord_polar(\"y\") +\n  labs(title = \"Composición por escala (cuantitativas)\", x = NULL, y = NULL) +\n  theme_minimal(base_size = 11.5) +\n  theme(plot.background = element_rect(fill = \"white\", colour = NA),\n        plot.title = element_text(colour = \"#1a3a5c\", face = \"bold\", size = 11.5),\n        legend.title = element_blank(), legend.text = element_text(size = 9),\n        axis.text = element_blank(), panel.grid = element_blank())\n```\n\n::: {.cell-output-display}\n![Composición porcentual de las variables cuantitativas por escala](descripcion_files/figure-html/general-tipos-cuanti-2.png){width=100%}\n:::\n:::\n\n\nEntre las 12 variables cuantitativas se cuenta con 11 en escala de razón y 1 en escala de intervalo. Hay presencia de variables de tipo entero y numérico asociadas a conteos y puntajes respectivamente. Se tiene que 7 de estas variables hacen parte del conjunto de datos original mientras que otras 5 fueron agregadas con enriquecimiento (Ver [Conjunto de Datos y Enriquecimiento](dataset.qmd)).\n\n### Valores faltantes\n\n::: {.cell tbl-cap='Valores perdidos por variable'}\n\n```{.r .cell-code}\ntibble::tibble(Variable = names(datos), Perdidos = as.integer(colSums(is.na(datos)))) |>\n  dplyr::filter(Perdidos > 0) |>\n  dplyr::mutate(`% de las filas` = pct(100 * Perdidos / nrow(datos))) |>\n  dplyr::arrange(dplyr::desc(Perdidos)) |>\n  dplyr::mutate(Perdidos = ent(Perdidos)) |>\n  knitr::kable(col.names = c(\"Variable\", \"Valores perdidos\", \"% de las filas\"),\n               align = c(\"l\", \"r\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\n|Variable            | Valores perdidos| % de las filas|\n|:-------------------|----------------:|--------------:|\n|Name                |            1.257|          8,4 %|\n|sentiment_score     |              551|          3,7 %|\n|sentiment_magnitude |              551|          3,7 %|\n|total_labels        |              341|          2,3 %|\n|total_faces         |              341|          2,3 %|\n|total_colors        |              341|          2,3 %|\n\n\n:::\n:::\n\n\nLa variable nombre y otras cinco variables derivadas del enriquecimiento presentan datos faltantes. El nombre del animal tiene 1.257 casos faltantes, las dos variables de sentimiento 551 cada una y las tres variables derivadas de la imagen 341 cada una (son anuncios sin fotografía).\n\n### Resumen\nEl conjunto de datos tiene 14.993 unidades de observación (los anuncios), 31 variables y 464.783 celdas, de las cuales se pierde el 0,73 %; ese porcentaje es bajo y está concentrado en seis variables de las cuales cinco variables pertenecen al enriquecimiento. Los 0 duplicados de fila y de identificador confirman que no hay anuncios repetidos. En cuanto a la composición, hay 12 variables cuantitativas (39 % del total) y 19 cualitativas (61 %), de modo que el análisis descriptivo es parcialmente balanceado respecto al tipo de variables. Se considera importante tener presente que hay variables **casi constantes** (`Health`, `total_faces`, `VideoAmt`) y variables **de alta cardinalidad** (`Breed1`, `State`, `Name`, `Description`) que requieren un tratamiento distinto. Los detalles se retoman en las secciones siguientes.",
    "supporting": [
      "descripcion_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}